-- ============================================================================
-- CREATE TABLES (check-add mode) - Idempotent schema, never drops columns
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Tables: 8
-- Total Raw Fields: 59
-- ============================================================================

SET timezone = 'UTC';

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- SiteSettings: Singleton table of site-wide facts: contact info, positioning statement, and the undated 'Currently' block. One row.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS site_settings (
  site_setting_id                     TEXT                 PRIMARY KEY          -- Stored identity of the singleton settings row.
);
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS contact_email TEXT;                              -- Primary contact email, shown in the Contact section on Home and Work.
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS contact_phone TEXT;                              -- Contact phone number, as it appears on the resume header.
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS site_domain TEXT;                                -- Canonical site domain.
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS portfolio_company_count TEXT;                    -- Standardized portfolio count string, per Content Strategy Section 6 ('100+' everywhere, never 107 or 111).
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS self_description_line TEXT;                      -- The 'full stack product practitioner' anchor phrase. Per Section 2: say it once, never next to a list.
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS positioning_statement TEXT;                      -- The core positioning paragraph everything else derives from (Content Strategy Section 2).
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS currently_text TEXT;                             -- PLACEHOLDER, not yet approved copy. The undated 'Currently' block on Home (Section 10): 2-3 lines on what David is working on now. Update when something changes, not on a schedule. Confirm real wording with David before shipping.
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS banyan_title TEXT;                               -- Full Banyan title, used everywhere per Section 6: 'Technical Advisor, Product Strategy and UX'.
COMMENT ON TABLE site_settings IS 'Singleton table of site-wide facts: contact info, positioning statement, and the undated ''Currently'' block. One row.';
COMMENT ON COLUMN site_settings.site_setting_id IS 'Stored identity of the singleton settings row.';
COMMENT ON COLUMN site_settings.contact_email IS 'Primary contact email, shown in the Contact section on Home and Work.';
COMMENT ON COLUMN site_settings.contact_phone IS 'Contact phone number, as it appears on the resume header.';
COMMENT ON COLUMN site_settings.site_domain IS 'Canonical site domain.';
COMMENT ON COLUMN site_settings.portfolio_company_count IS 'Standardized portfolio count string, per Content Strategy Section 6 (''100+'' everywhere, never 107 or 111).';
COMMENT ON COLUMN site_settings.self_description_line IS 'The ''full stack product practitioner'' anchor phrase. Per Section 2: say it once, never next to a list.';
COMMENT ON COLUMN site_settings.positioning_statement IS 'The core positioning paragraph everything else derives from (Content Strategy Section 2).';
COMMENT ON COLUMN site_settings.currently_text IS 'PLACEHOLDER, not yet approved copy. The undated ''Currently'' block on Home (Section 10): 2-3 lines on what David is working on now. Update when something changes, not on a schedule. Confirm real wording with David before shipping.';
COMMENT ON COLUMN site_settings.banyan_title IS 'Full Banyan title, used everywhere per Section 6: ''Technical Advisor, Product Strategy and UX''.';

-- ----------------------------------------------------------------------------
-- BioVariants: Table: BioVariants. Five lengths plus one alternate, one spine, per David_Shadle_Bio_Set_v1.md. Voice standard applied: no em dashes, short sentences, active voice, no filler.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bio_variants (
  bio_variant_id                      TEXT                 PRIMARY KEY          -- Stored identity, slug form.
);
ALTER TABLE bio_variants ADD COLUMN IF NOT EXISTS label TEXT;                                       -- Human label for this bio length/context, e.g. 'Fifty words'.
ALTER TABLE bio_variants ADD COLUMN IF NOT EXISTS usage_context TEXT;                               -- Where this variant gets used, e.g. 'Directory listings, conference programs, deck footers, introductions.'
ALTER TABLE bio_variants ADD COLUMN IF NOT EXISTS body_text TEXT;                                   -- The bio copy itself. Paragraph breaks encoded as \n\n.
ALTER TABLE bio_variants ADD COLUMN IF NOT EXISTS sort_order INTEGER;                               -- Display order, shortest to longest.
COMMENT ON TABLE bio_variants IS 'Table: BioVariants. Five lengths plus one alternate, one spine, per David_Shadle_Bio_Set_v1.md. Voice standard applied: no em dashes, short sentences, active voice, no filler.';
COMMENT ON COLUMN bio_variants.bio_variant_id IS 'Stored identity, slug form.';
COMMENT ON COLUMN bio_variants.label IS 'Human label for this bio length/context, e.g. ''Fifty words''.';
COMMENT ON COLUMN bio_variants.usage_context IS 'Where this variant gets used, e.g. ''Directory listings, conference programs, deck footers, introductions.''';
COMMENT ON COLUMN bio_variants.body_text IS 'The bio copy itself. Paragraph breaks encoded as \n\n.';
COMMENT ON COLUMN bio_variants.sort_order IS 'Display order, shortest to longest.';

-- ----------------------------------------------------------------------------
-- HowIWorkSections: Table: HowIWorkSections. The method statement for the How I Work page, per David_Shadle_How_I_Work_v1.md. Written to be true indefinitely.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS how_i_work_sections (
  how_i_work_section_id               TEXT                 PRIMARY KEY          -- Stored identity, slug form.
);
ALTER TABLE how_i_work_sections ADD COLUMN IF NOT EXISTS heading TEXT;                              -- Section heading as it appears on the page.
ALTER TABLE how_i_work_sections ADD COLUMN IF NOT EXISTS body_text TEXT;                            -- Full-page body copy for this section. Paragraph breaks encoded as \n\n.
ALTER TABLE how_i_work_sections ADD COLUMN IF NOT EXISTS short_body_text TEXT;                      -- Condensed ~1-paragraph version, used if How I Work becomes a Home section instead of its own page. Null where the short version drops the section entirely.
ALTER TABLE how_i_work_sections ADD COLUMN IF NOT EXISTS sort_order INTEGER;                        -- Display order on the page.
COMMENT ON TABLE how_i_work_sections IS 'Table: HowIWorkSections. The method statement for the How I Work page, per David_Shadle_How_I_Work_v1.md. Written to be true indefinitely.';
COMMENT ON COLUMN how_i_work_sections.how_i_work_section_id IS 'Stored identity, slug form.';
COMMENT ON COLUMN how_i_work_sections.heading IS 'Section heading as it appears on the page.';
COMMENT ON COLUMN how_i_work_sections.body_text IS 'Full-page body copy for this section. Paragraph breaks encoded as \n\n.';
COMMENT ON COLUMN how_i_work_sections.short_body_text IS 'Condensed ~1-paragraph version, used if How I Work becomes a Home section instead of its own page. Null where the short version drops the section entirely.';
COMMENT ON COLUMN how_i_work_sections.sort_order IS 'Display order on the page.';

-- ----------------------------------------------------------------------------
-- ProofPoints: Table: ProofPoints. The proof inventory from Content Strategy Section 4. Raw material for the Work page and the resume's Selected Work block. Nothing goes into a bio, resume, or Work page entry that is not traceable to a row here.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS proof_points (
  proof_point_id                      TEXT                 PRIMARY KEY          -- Stored identity, slug form, matches Content Strategy subsection (e.g. 'pm-portal' for 4.2).
);
ALTER TABLE proof_points ADD COLUMN IF NOT EXISTS title TEXT;                                       -- Short title for this proof point.
ALTER TABLE proof_points ADD COLUMN IF NOT EXISTS problem_text TEXT;                                -- The problem, as stated in the proof inventory.
ALTER TABLE proof_points ADD COLUMN IF NOT EXISTS action_text TEXT;                                 -- The action taken.
ALTER TABLE proof_points ADD COLUMN IF NOT EXISTS outcome_text TEXT;                                -- The outcome.
ALTER TABLE proof_points ADD COLUMN IF NOT EXISTS attribution_note TEXT;                            -- Precise attribution language required when describing this work (e.g. 'advised on and implemented,' not 'owned'). See Content Strategy Section 6.
ALTER TABLE proof_points ADD COLUMN IF NOT EXISTS register_note TEXT;                               -- Internal guidance on tone/register for this proof point. Not published copy - for whoever writes site/resume text from this row.
ALTER TABLE proof_points ADD COLUMN IF NOT EXISTS featured_on_work_page BOOLEAN;                    -- Whether this proof point is one of the 2-3 engagements shown on the Work page (Section 10). First-pass selection - confirm with David before Phase 2.
ALTER TABLE proof_points ADD COLUMN IF NOT EXISTS featured_in_resume_selected_work BOOLEAN;         -- Whether this proof point appears in the resume's 'Selected work, 2024 to 2026' block (Variant A).
ALTER TABLE proof_points ADD COLUMN IF NOT EXISTS sort_order INTEGER;                               -- Order matching Content Strategy Section 4 numbering.
COMMENT ON TABLE proof_points IS 'Table: ProofPoints. The proof inventory from Content Strategy Section 4. Raw material for the Work page and the resume''s Selected Work block. Nothing goes into a bio, resume, or Work page entry that is not traceable to a row here.';
COMMENT ON COLUMN proof_points.proof_point_id IS 'Stored identity, slug form, matches Content Strategy subsection (e.g. ''pm-portal'' for 4.2).';
COMMENT ON COLUMN proof_points.title IS 'Short title for this proof point.';
COMMENT ON COLUMN proof_points.problem_text IS 'The problem, as stated in the proof inventory.';
COMMENT ON COLUMN proof_points.action_text IS 'The action taken.';
COMMENT ON COLUMN proof_points.outcome_text IS 'The outcome.';
COMMENT ON COLUMN proof_points.attribution_note IS 'Precise attribution language required when describing this work (e.g. ''advised on and implemented,'' not ''owned''). See Content Strategy Section 6.';
COMMENT ON COLUMN proof_points.register_note IS 'Internal guidance on tone/register for this proof point. Not published copy - for whoever writes site/resume text from this row.';
COMMENT ON COLUMN proof_points.featured_on_work_page IS 'Whether this proof point is one of the 2-3 engagements shown on the Work page (Section 10). First-pass selection - confirm with David before Phase 2.';
COMMENT ON COLUMN proof_points.featured_in_resume_selected_work IS 'Whether this proof point appears in the resume''s ''Selected work, 2024 to 2026'' block (Variant A).';
COMMENT ON COLUMN proof_points.sort_order IS 'Order matching Content Strategy Section 4 numbering.';

-- ----------------------------------------------------------------------------
-- JobEntries: Table: JobEntries. Career history, shared by both resume variants via inclusion flags rather than duplicated per variant. Rows are grouped by DisplayGroupKey where a variant collapses multiple rows into one displayed entry (e.g. Variant A merges the two Power Automate roles).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS job_entries (
  job_entries_id                      TEXT                 PRIMARY KEY          -- Primary key (synthesized from the calculated Name — the table's logical key — so it wins over incidental Id-ending attribute fields).
);
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS job_entry_id TEXT;                                 -- Stored identity, slug form.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS company TEXT;                                      -- Employer or entity name.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS job_title TEXT;                                    -- Title held. Null on the single synthetic 'earlier roles' compressed row.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS start_date DATE;                                   -- Start, YYYY-MM.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS end_date DATE;                                     -- End, YYYY-MM. Null if current.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS is_current BOOLEAN;                                -- True if this role is ongoing.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS display_group_key TEXT;                            -- Rows sharing this key render as one entry in Variant A (which uses the coarser grouping). Null where no grouping applies.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS summary_text_variant_a TEXT;                       -- Prose summary as it appears in Resume Variant A. On a grouped pair, only the earliest row in the group carries the merged text; the later row is null and the app renders the group using the earliest row's text with the group's full date range.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS summary_text_variant_b TEXT;                       -- Bullet-point summary as it appears in Resume Variant B, bullets joined with \n.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS compressed_line TEXT;                              -- One-line compressed text, used only on the synthetic 'earlier roles' row for Variant A's single-line pre-2019 summary.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS include_in_variant_a BOOLEAN;                      -- Whether this row is shown (individually or as part of a group) on Resume Variant A.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS include_in_variant_b BOOLEAN;                      -- Whether this row is shown on Resume Variant B.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS is_pre2019 BOOLEAN;                                -- True for roles before 2019, compressed in Variant A per Content Strategy Section 7.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS sort_order INTEGER;                                -- Reverse chronological display order.
COMMENT ON TABLE job_entries IS 'Table: JobEntries. Career history, shared by both resume variants via inclusion flags rather than duplicated per variant. Rows are grouped by DisplayGroupKey where a variant collapses multiple rows into one displayed entry (e.g. Variant A merges the two Power Automate roles).';
COMMENT ON COLUMN job_entries.job_entries_id IS 'Primary key (synthesized from the calculated Name — the table''s logical key — so it wins over incidental Id-ending attribute fields).';
COMMENT ON COLUMN job_entries.job_entry_id IS 'Stored identity, slug form.';
COMMENT ON COLUMN job_entries.company IS 'Employer or entity name.';
COMMENT ON COLUMN job_entries.job_title IS 'Title held. Null on the single synthetic ''earlier roles'' compressed row.';
COMMENT ON COLUMN job_entries.start_date IS 'Start, YYYY-MM.';
COMMENT ON COLUMN job_entries.end_date IS 'End, YYYY-MM. Null if current.';
COMMENT ON COLUMN job_entries.is_current IS 'True if this role is ongoing.';
COMMENT ON COLUMN job_entries.display_group_key IS 'Rows sharing this key render as one entry in Variant A (which uses the coarser grouping). Null where no grouping applies.';
COMMENT ON COLUMN job_entries.summary_text_variant_a IS 'Prose summary as it appears in Resume Variant A. On a grouped pair, only the earliest row in the group carries the merged text; the later row is null and the app renders the group using the earliest row''s text with the group''s full date range.';
COMMENT ON COLUMN job_entries.summary_text_variant_b IS 'Bullet-point summary as it appears in Resume Variant B, bullets joined with \n.';
COMMENT ON COLUMN job_entries.compressed_line IS 'One-line compressed text, used only on the synthetic ''earlier roles'' row for Variant A''s single-line pre-2019 summary.';
COMMENT ON COLUMN job_entries.include_in_variant_a IS 'Whether this row is shown (individually or as part of a group) on Resume Variant A.';
COMMENT ON COLUMN job_entries.include_in_variant_b IS 'Whether this row is shown on Resume Variant B.';
COMMENT ON COLUMN job_entries.is_pre2019 IS 'True for roles before 2019, compressed in Variant A per Content Strategy Section 7.';
COMMENT ON COLUMN job_entries.sort_order IS 'Reverse chronological display order.';

-- ----------------------------------------------------------------------------
-- ResumeVariants: Table: ResumeVariants. Two variants, one spine, per David_Shadle_Resume_Variants_v1.md. Variant A is public/served from the site; Variant B is sent directly and never published.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS resume_variants (
  resume_variant_id                   TEXT                 PRIMARY KEY          -- Stored identity, slug form.
);
ALTER TABLE resume_variants ADD COLUMN IF NOT EXISTS label TEXT;                                    -- Variant label.
ALTER TABLE resume_variants ADD COLUMN IF NOT EXISTS audience_description TEXT;                     -- Who this variant targets and how it is distributed.
ALTER TABLE resume_variants ADD COLUMN IF NOT EXISTS summary_text TEXT;                             -- The opening capability statement ('What I do' / 'Summary'). Paragraph breaks encoded as \n\n.
ALTER TABLE resume_variants ADD COLUMN IF NOT EXISTS published_on_site BOOLEAN;                     -- Whether this variant is served from the public site (Section 10: only Variant A).
COMMENT ON TABLE resume_variants IS 'Table: ResumeVariants. Two variants, one spine, per David_Shadle_Resume_Variants_v1.md. Variant A is public/served from the site; Variant B is sent directly and never published.';
COMMENT ON COLUMN resume_variants.resume_variant_id IS 'Stored identity, slug form.';
COMMENT ON COLUMN resume_variants.label IS 'Variant label.';
COMMENT ON COLUMN resume_variants.audience_description IS 'Who this variant targets and how it is distributed.';
COMMENT ON COLUMN resume_variants.summary_text IS 'The opening capability statement (''What I do'' / ''Summary''). Paragraph breaks encoded as \n\n.';
COMMENT ON COLUMN resume_variants.published_on_site IS 'Whether this variant is served from the public site (Section 10: only Variant A).';

-- ----------------------------------------------------------------------------
-- ResumeListItems: Table: ResumeListItems. The Methods and Technical blocks, shared identically by both resume variants, replacing the old comma-separated skills paragraph.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS resume_list_items (
  resume_list_item_id                 TEXT                 PRIMARY KEY          -- Stored identity, slug form.
);
ALTER TABLE resume_list_items ADD COLUMN IF NOT EXISTS category TEXT;                               -- 'Methods' or 'Technical'.
ALTER TABLE resume_list_items ADD COLUMN IF NOT EXISTS label TEXT;                                  -- The item text as it appears on the resume.
ALTER TABLE resume_list_items ADD COLUMN IF NOT EXISTS sort_order INTEGER;                          -- Display order within its category.
COMMENT ON TABLE resume_list_items IS 'Table: ResumeListItems. The Methods and Technical blocks, shared identically by both resume variants, replacing the old comma-separated skills paragraph.';
COMMENT ON COLUMN resume_list_items.resume_list_item_id IS 'Stored identity, slug form.';
COMMENT ON COLUMN resume_list_items.category IS '''Methods'' or ''Technical''.';
COMMENT ON COLUMN resume_list_items.label IS 'The item text as it appears on the resume.';
COMMENT ON COLUMN resume_list_items.sort_order IS 'Display order within its category.';

-- ----------------------------------------------------------------------------
-- EducationEntries: Table: EducationEntries.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS education_entries (
  education_entries_id                TEXT                 PRIMARY KEY          -- Primary key (synthesized from the calculated Name — the table's logical key — so it wins over incidental Id-ending attribute fields).
);
ALTER TABLE education_entries ADD COLUMN IF NOT EXISTS education_entry_id TEXT;                     -- Stored identity, slug form.
ALTER TABLE education_entries ADD COLUMN IF NOT EXISTS institution TEXT;                            -- School name.
ALTER TABLE education_entries ADD COLUMN IF NOT EXISTS degree TEXT;                                 -- Degree earned.
ALTER TABLE education_entries ADD COLUMN IF NOT EXISTS field_of_study TEXT;                         -- Major/field.
ALTER TABLE education_entries ADD COLUMN IF NOT EXISTS grad_year INTEGER;                           -- Graduation year.
COMMENT ON TABLE education_entries IS 'Table: EducationEntries.';
COMMENT ON COLUMN education_entries.education_entries_id IS 'Primary key (synthesized from the calculated Name — the table''s logical key — so it wins over incidental Id-ending attribute fields).';
COMMENT ON COLUMN education_entries.education_entry_id IS 'Stored identity, slug form.';
COMMENT ON COLUMN education_entries.institution IS 'School name.';
COMMENT ON COLUMN education_entries.degree IS 'Degree earned.';
COMMENT ON COLUMN education_entries.field_of_study IS 'Major/field.';
COMMENT ON COLUMN education_entries.grad_year IS 'Graduation year.';

-- ============================================================================
-- FK INDEXES - Performance only, always applied
-- ============================================================================

-- (no FK fields detected in rulebook)
