-- ============================================================================
-- CREATE FUNCTIONS - Calculation functions for lookup/calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- ============================================================================


-- Disable body validation so LANGUAGE sql functions can forward-reference
-- each other within this file. (pg_dump does the same thing for the same
-- reason.) Without this, SQL functions parse-check at CREATE time and fail
-- on the first forward call site; plpgsql didn't, which is how this file
-- ever worked. Dependency order is still enforced at EXECUTION time.
SET check_function_bodies = off;

-- ============================================================================
-- ERB BUILD PARAMETERS (docs/ERB-BUILD-PARAMETERS.md)
-- erbBlankLogic=coerce, erbDateDiff=calendar, erbDateTimeText=iso8601, erbTimezone=UTC, erbWholeNumber=by-field-type
-- ============================================================================

CREATE OR REPLACE FUNCTION erb_build_parameters()
RETURNS JSONB AS $$
  SELECT '{"erbBlankLogic":"coerce","erbDateDiff":"calendar","erbDateTimeText":"iso8601","erbTimezone":"UTC","erbWholeNumber":"by-field-type"}'::jsonb;
$$ LANGUAGE sql IMMUTABLE;

-- A timestamp inside text, per erbDateTimeText, in erbTimezone. Blank renders ''.
CREATE OR REPLACE FUNCTION erb_datetime_text(ts TIMESTAMPTZ)
RETURNS TEXT AS $$
  SELECT CASE WHEN ts IS NULL THEN '' ELSE
    to_char(ts AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS')
    || CASE WHEN (EXTRACT(MICROSECONDS FROM ts)::bigint % 1000000) <> 0 THEN rtrim(to_char(ts AT TIME ZONE 'UTC', '.US'), '0') ELSE '' END
    || CASE WHEN o.off < 0 THEN '-' ELSE '+' END || lpad((abs(o.off) / 3600)::text, 2, '0') || ':' || lpad(((abs(o.off) % 3600) / 60)::text, 2, '0')
  END
  FROM (SELECT EXTRACT(EPOCH FROM ((ts AT TIME ZONE 'UTC') - (ts AT TIME ZONE 'UTC')))::integer AS off) o;
$$ LANGUAGE sql STABLE;

-- A date inside text: YYYY-MM-DD. Blank renders ''.
CREATE OR REPLACE FUNCTION erb_date_text(d DATE)
RETURNS TEXT AS $$
  SELECT COALESCE(to_char(d, 'YYYY-MM-DD'), '');
$$ LANGUAGE sql IMMUTABLE;

-- A number inside text: the shortest exact form, no trailing .0 (2, 2.5). Blank renders ''.
CREATE OR REPLACE FUNCTION erb_number_text(n NUMERIC)
RETURNS TEXT AS $$
  SELECT CASE WHEN n IS NULL THEN ''
              WHEN n::text LIKE '%.%' THEN rtrim(rtrim(n::text, '0'), '.')
              ELSE n::text END;
$$ LANGUAGE sql IMMUTABLE;


-- ============================================================================
-- LOOKUP FUNCTIONS
-- These functions perform lookups via foreign key relationships
-- ============================================================================

-- calc_site_settings_name
-- Field: SiteSettings.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_site_settings_name(p_site_setting_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(site_setting_id, '') FROM site_settings WHERE site_setting_id = p_site_setting_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_currently_items_name
-- Field: CurrentlyItems.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_currently_items_name(p_currently_item_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(title, '') FROM currently_items WHERE currently_item_id = p_currently_item_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_bio_variants_name
-- Field: BioVariants.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_bio_variants_name(p_bio_variant_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(label, '') FROM bio_variants WHERE bio_variant_id = p_bio_variant_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_how_i_work_sections_name
-- Field: HowIWorkSections.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_how_i_work_sections_name(p_how_i_work_section_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(heading, '') FROM how_i_work_sections WHERE how_i_work_section_id = p_how_i_work_section_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_proof_points_name
-- Field: ProofPoints.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_proof_points_name(p_proof_point_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(title, '') FROM proof_points WHERE proof_point_id = p_proof_point_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_job_entries_name
-- Field: JobEntries.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_job_entries_name(p_job_entry_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(company, '') FROM job_entries WHERE job_entry_id = p_job_entry_id), ' - ', (SELECT NULLIF(job_title, '') FROM job_entries WHERE job_entry_id = p_job_entry_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_resume_variants_name
-- Field: ResumeVariants.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_resume_variants_name(p_resume_variant_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(label, '') FROM resume_variants WHERE resume_variant_id = p_resume_variant_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_resume_list_items_name
-- Field: ResumeListItems.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_resume_list_items_name(p_resume_list_item_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(label, '') FROM resume_list_items WHERE resume_list_item_id = p_resume_list_item_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_education_entries_name
-- Field: EducationEntries.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_education_entries_name(p_education_entry_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(institution, '') FROM education_entries WHERE education_entry_id = p_education_entry_id), ' - ', (SELECT NULLIF(degree, '') FROM education_entries WHERE education_entry_id = p_education_entry_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_landing_pages_name
-- Field: LandingPages.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_landing_pages_name(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(headline, '') FROM landing_pages WHERE landing_page_id = p_landing_page_id))::text;
$$ LANGUAGE sql STABLE;

-- get_landing_pages_meta_title
-- Helper function: Get MetaTitle from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_meta_title(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT meta_title FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- get_landing_pages_meta_description
-- Helper function: Get MetaDescription from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_meta_description(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT meta_description FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- get_landing_pages_eyebrow
-- Helper function: Get Eyebrow from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_eyebrow(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT eyebrow FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- get_landing_pages_headline
-- Helper function: Get Headline from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_headline(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT headline FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- get_landing_pages_lede
-- Helper function: Get Lede from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_lede(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT lede FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- get_landing_pages_video_url
-- Helper function: Get VideoUrl from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_video_url(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT video_url FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- get_landing_pages_primary_cta_label
-- Helper function: Get PrimaryCtaLabel from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_primary_cta_label(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT primary_cta_label FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- get_landing_pages_primary_cta_href
-- Helper function: Get PrimaryCtaHref from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_primary_cta_href(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT primary_cta_href FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- get_landing_pages_secondary_cta_label
-- Helper function: Get SecondaryCtaLabel from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_secondary_cta_label(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT secondary_cta_label FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- get_landing_pages_secondary_cta_href
-- Helper function: Get SecondaryCtaHref from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_secondary_cta_href(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT secondary_cta_href FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- get_landing_pages_is_published
-- Helper function: Get IsPublished from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_is_published(p_landing_page_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT is_published FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- calc_landing_page_sections_name
-- Field: LandingPageSections.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_landing_page_sections_name(p_landing_page_section_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(heading, '') FROM landing_page_sections WHERE landing_page_section_id = p_landing_page_section_id))::text;
$$ LANGUAGE sql STABLE;

-- get_landing_page_sections_sort_order
-- Helper function: Get SortOrder from LandingPageSections by LandingPageSectionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_page_sections_sort_order(p_landing_page_section_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT sort_order FROM landing_page_sections WHERE landing_page_section_id = p_landing_page_section_id);
$$ LANGUAGE sql STABLE;

-- get_landing_page_sections_kind
-- Helper function: Get Kind from LandingPageSections by LandingPageSectionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_page_sections_kind(p_landing_page_section_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT kind FROM landing_page_sections WHERE landing_page_section_id = p_landing_page_section_id);
$$ LANGUAGE sql STABLE;

-- get_landing_page_sections_eyebrow
-- Helper function: Get Eyebrow from LandingPageSections by LandingPageSectionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_page_sections_eyebrow(p_landing_page_section_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT eyebrow FROM landing_page_sections WHERE landing_page_section_id = p_landing_page_section_id);
$$ LANGUAGE sql STABLE;

-- get_landing_page_sections_heading
-- Helper function: Get Heading from LandingPageSections by LandingPageSectionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_page_sections_heading(p_landing_page_section_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT heading FROM landing_page_sections WHERE landing_page_section_id = p_landing_page_section_id);
$$ LANGUAGE sql STABLE;

-- get_landing_page_sections_body_text
-- Helper function: Get BodyText from LandingPageSections by LandingPageSectionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_page_sections_body_text(p_landing_page_section_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT body_text FROM landing_page_sections WHERE landing_page_section_id = p_landing_page_section_id);
$$ LANGUAGE sql STABLE;

-- get_landing_page_sections_link_label
-- Helper function: Get LinkLabel from LandingPageSections by LandingPageSectionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_page_sections_link_label(p_landing_page_section_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT link_label FROM landing_page_sections WHERE landing_page_section_id = p_landing_page_section_id);
$$ LANGUAGE sql STABLE;

-- get_landing_page_sections_link_href
-- Helper function: Get LinkHref from LandingPageSections by LandingPageSectionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_page_sections_link_href(p_landing_page_section_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT link_href FROM landing_page_sections WHERE landing_page_section_id = p_landing_page_section_id);
$$ LANGUAGE sql STABLE;

-- calc_landing_page_items_name
-- Field: LandingPageItems.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_landing_page_items_name(p_landing_page_item_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(heading, '') FROM landing_page_items WHERE landing_page_item_id = p_landing_page_item_id))::text;
$$ LANGUAGE sql STABLE;

-- get_landing_page_items_sort_order
-- Helper function: Get SortOrder from LandingPageItems by LandingPageItemId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_page_items_sort_order(p_landing_page_item_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT sort_order FROM landing_page_items WHERE landing_page_item_id = p_landing_page_item_id);
$$ LANGUAGE sql STABLE;

-- get_landing_page_items_label
-- Helper function: Get Label from LandingPageItems by LandingPageItemId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_page_items_label(p_landing_page_item_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT label FROM landing_page_items WHERE landing_page_item_id = p_landing_page_item_id);
$$ LANGUAGE sql STABLE;

-- get_landing_page_items_heading
-- Helper function: Get Heading from LandingPageItems by LandingPageItemId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_page_items_heading(p_landing_page_item_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT heading FROM landing_page_items WHERE landing_page_item_id = p_landing_page_item_id);
$$ LANGUAGE sql STABLE;

-- get_landing_page_items_body_text
-- Helper function: Get BodyText from LandingPageItems by LandingPageItemId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_page_items_body_text(p_landing_page_item_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT body_text FROM landing_page_items WHERE landing_page_item_id = p_landing_page_item_id);
$$ LANGUAGE sql STABLE;

-- calc_landing_page_item_facts_name
-- Field: LandingPageItemFacts.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_landing_page_item_facts_name(p_landing_page_item_fact_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(label, '') FROM landing_page_item_facts WHERE landing_page_item_fact_id = p_landing_page_item_fact_id))::text;
$$ LANGUAGE sql STABLE;

-- ============================================================================
-- MANY-SIDE RELATIONSHIP FUNCTIONS
-- These functions aggregate child records for many-side relationships
-- ============================================================================

-- ============================================================================
-- INVERSE RELATIONSHIP FUNCTIONS
-- These functions perform reverse FK lookups for inverse-side relationships
-- ============================================================================

