-- ============================================================================
-- CREATE FUNCTIONS - Calculation functions for lookup/calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- ============================================================================


-- Disable body validation so LANGUAGE sql functions can forward-reference
-- each other within this file. (pg_dump does the same thing for the same
-- reason.) Without this, SQL functions parse-check at CREATE time and fail
-- on the first forward call site; plpgsql didn't, which is how this file
-- ever worked. Dependency order is still enforced at EXECUTION time.
SET check_function_bodies = off;

-- ============================================================================
-- LOOKUP FUNCTIONS
-- These functions perform lookups via foreign key relationships
-- ============================================================================

-- calc_site_settings_name
-- Field: SiteSettings.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_site_settings_name(p_site_setting_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(site_setting_id, '') FROM site_settings WHERE site_setting_id = p_site_setting_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_currently_items_name
-- Field: CurrentlyItems.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_currently_items_name(p_currently_item_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(currently_item_id, '') FROM currently_items WHERE currently_item_id = p_currently_item_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_bio_variants_name
-- Field: BioVariants.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_bio_variants_name(p_bio_variant_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(label, '') FROM bio_variants WHERE bio_variant_id = p_bio_variant_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_how_i_work_sections_name
-- Field: HowIWorkSections.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_how_i_work_sections_name(p_how_i_work_section_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(heading, '') FROM how_i_work_sections WHERE how_i_work_section_id = p_how_i_work_section_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_proof_points_name
-- Field: ProofPoints.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_proof_points_name(p_proof_point_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(title, '') FROM proof_points WHERE proof_point_id = p_proof_point_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_job_entries_name
-- Field: JobEntries.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_job_entries_name(p_job_entries_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(company, '') FROM job_entries WHERE job_entries_id = p_job_entries_id), ' - ', (SELECT NULLIF(job_title, '') FROM job_entries WHERE job_entries_id = p_job_entries_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_resume_variants_name
-- Field: ResumeVariants.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_resume_variants_name(p_resume_variant_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(label, '') FROM resume_variants WHERE resume_variant_id = p_resume_variant_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_resume_list_items_name
-- Field: ResumeListItems.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_resume_list_items_name(p_resume_list_item_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(label, '') FROM resume_list_items WHERE resume_list_item_id = p_resume_list_item_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_education_entries_name
-- Field: EducationEntries.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_education_entries_name(p_education_entries_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(institution, '') FROM education_entries WHERE education_entries_id = p_education_entries_id), ' - ', (SELECT NULLIF(degree, '') FROM education_entries WHERE education_entries_id = p_education_entries_id)))::text;
$$ LANGUAGE sql STABLE;

-- ============================================================================
-- MANY-SIDE RELATIONSHIP FUNCTIONS
-- These functions aggregate child records for many-side relationships
-- ============================================================================

-- ============================================================================
-- INVERSE RELATIONSHIP FUNCTIONS
-- These functions perform reverse FK lookups for inverse-side relationships
-- ============================================================================

