-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Views: 8
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Drop pass: every rulebook-owned view, reverse iteration order, CASCADE.
-- The rulebook is HEAD — the surviving view set must mirror it exactly.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_education_entries CASCADE;
DROP VIEW IF EXISTS vw_resume_list_items CASCADE;
DROP VIEW IF EXISTS vw_resume_variants CASCADE;
DROP VIEW IF EXISTS vw_job_entries CASCADE;
DROP VIEW IF EXISTS vw_proof_points CASCADE;
DROP VIEW IF EXISTS vw_how_i_work_sections CASCADE;
DROP VIEW IF EXISTS vw_bio_variants CASCADE;
DROP VIEW IF EXISTS vw_site_settings CASCADE;

-- ----------------------------------------------------------------------------
-- vw_site_settings: Singleton table of site-wide facts: contact info, positioning statement, and the undated 'Currently' block. One row.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_site_settings CASCADE;
CREATE VIEW vw_site_settings WITH (security_invoker = ON) AS
SELECT
  t.site_setting_id,                                                            -- Stored identity of the singleton settings row.
  calc_site_settings_name(t.site_setting_id) AS name,                           -- Display alias.
  t.contact_email,                                                              -- Primary contact email, shown in the Contact section on Home and Work.
  t.contact_phone,                                                              -- Contact phone number, as it appears on the resume header.
  t.site_domain,                                                                -- Canonical site domain.
  t.portfolio_company_count,                                                    -- Standardized portfolio count string, per Content Strategy Section 6 ('100+' everywhere, never 107 or 111).
  t.self_description_line,                                                      -- The 'full stack product practitioner' anchor phrase. Per Section 2: say it once, never next to a list.
  t.positioning_statement,                                                      -- The core positioning paragraph everything else derives from (Content Strategy Section 2).
  t.hero_headline,                                                              -- The large opening line of the Home hero, first person. First sentence of PositioningStatement, curated separately so the hero can style it distinctly from HeroSubheadline.
  t.hero_subheadline,                                                           -- The medium-sized second line of the Home hero, directly under HeroHeadline. Second/third sentence of PositioningStatement.
  t.currently_text,                                                             -- The undated 'Currently' block on Home (Section 10): 2-3 lines on what David is working on now. Update when something changes, not on a schedule.
  t.banyan_title                                                                -- Full Banyan title, used everywhere per Section 6: 'Technical Advisor, Product Strategy and UX'.
FROM site_settings t;

-- ----------------------------------------------------------------------------
-- vw_bio_variants: Table: BioVariants. Five lengths plus one alternate, one spine, per David_Shadle_Bio_Set_v1.md. Voice standard applied: no em dashes, short sentences, active voice, no filler.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_bio_variants CASCADE;
CREATE VIEW vw_bio_variants WITH (security_invoker = ON) AS
SELECT
  t.bio_variant_id,                                                             -- Stored identity, slug form.
  calc_bio_variants_name(t.bio_variant_id) AS name,                             -- Display alias.
  t.label,                                                                      -- Human label for this bio length/context, e.g. 'Fifty words'.
  t.usage_context,                                                              -- Where this variant gets used, e.g. 'Directory listings, conference programs, deck footers, introductions.'
  t.body_text,                                                                  -- The bio copy itself. Paragraph breaks encoded as \n\n.
  t.sort_order                                                                  -- Display order, shortest to longest.
FROM bio_variants t;

-- ----------------------------------------------------------------------------
-- vw_how_i_work_sections: Table: HowIWorkSections. The method statement for the How I Work page, per David_Shadle_How_I_Work_v1.md. Written to be true indefinitely.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_how_i_work_sections CASCADE;
CREATE VIEW vw_how_i_work_sections WITH (security_invoker = ON) AS
SELECT
  t.how_i_work_section_id,                                                      -- Stored identity, slug form.
  calc_how_i_work_sections_name(t.how_i_work_section_id) AS name,               -- Display alias.
  t.heading,                                                                    -- Section heading as it appears on the page.
  t.body_text,                                                                  -- Full-page body copy for this section. Paragraph breaks encoded as \n\n.
  t.short_body_text,                                                            -- Condensed ~1-paragraph version, used if How I Work becomes a Home section instead of its own page. Null where the short version drops the section entirely.
  t.sort_order                                                                  -- Display order on the page.
FROM how_i_work_sections t;

-- ----------------------------------------------------------------------------
-- vw_proof_points: Table: ProofPoints. The proof inventory from Content Strategy Section 4. Raw material for the Work page and the resume's Selected Work block. Nothing goes into a bio, resume, or Work page entry that is not traceable to a row here.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_proof_points CASCADE;
CREATE VIEW vw_proof_points WITH (security_invoker = ON) AS
SELECT
  t.proof_point_id,                                                             -- Stored identity, slug form, matches Content Strategy subsection (e.g. 'pm-portal' for 4.2).
  calc_proof_points_name(t.proof_point_id) AS name,                             -- Display alias.
  t.title,                                                                      -- Short title for this proof point.
  t.problem_text,                                                               -- The problem, as stated in the proof inventory.
  t.action_text,                                                                -- The action taken.
  t.outcome_text,                                                               -- The outcome.
  t.attribution_note,                                                           -- Precise attribution language required when describing this work (e.g. 'advised on and implemented,' not 'owned'). See Content Strategy Section 6.
  t.register_note,                                                              -- Internal guidance on tone/register for this proof point. Not published copy - for whoever writes site/resume text from this row.
  t.featured_on_work_page,                                                      -- Whether this proof point is one of the 2-3 engagements shown on the Work page (Section 10). First-pass selection - confirm with David before Phase 2.
  t.featured_in_resume_selected_work,                                           -- Whether this proof point appears in the resume's 'Selected work, 2024 to 2026' block (Variant A).
  t.sort_order                                                                  -- Order matching Content Strategy Section 4 numbering.
FROM proof_points t;

-- ----------------------------------------------------------------------------
-- vw_job_entries: Table: JobEntries. Career history, shared by both resume variants via inclusion flags rather than duplicated per variant. Rows are grouped by DisplayGroupKey where a variant collapses multiple rows into one displayed entry (e.g. Variant A merges the two Power Automate roles).
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_job_entries CASCADE;
CREATE VIEW vw_job_entries WITH (security_invoker = ON) AS
SELECT
  t.job_entries_id,                                                             -- Primary key (synthesized from the calculated Name — the table's logical key — so it wins over incidental Id-ending attribute fields).
  t.job_entry_id,                                                               -- Stored identity, slug form.
  calc_job_entries_name(t.job_entries_id) AS name,                              -- Display alias.
  t.company,                                                                    -- Employer or entity name.
  t.job_title,                                                                  -- Title held. Null on the single synthetic 'earlier roles' compressed row.
  t.start_date,                                                                 -- Start, YYYY-MM.
  t.end_date,                                                                   -- End, YYYY-MM. Null if current.
  t.is_current,                                                                 -- True if this role is ongoing.
  t.display_group_key,                                                          -- Rows sharing this key render as one entry in Variant A (which uses the coarser grouping). Null where no grouping applies.
  t.summary_text_variant_a,                                                     -- Prose summary as it appears in Resume Variant A. On a grouped pair, only the earliest row in the group carries the merged text; the later row is null and the app renders the group using the earliest row's text with the group's full date range.
  t.summary_text_variant_b,                                                     -- Bullet-point summary as it appears in Resume Variant B, bullets joined with \n.
  t.compressed_line,                                                            -- One-line compressed text, used only on the synthetic 'earlier roles' row for Variant A's single-line pre-2019 summary.
  t.include_in_variant_a,                                                       -- Whether this row is shown (individually or as part of a group) on Resume Variant A.
  t.include_in_variant_b,                                                       -- Whether this row is shown on Resume Variant B.
  t.is_pre2019,                                                                 -- True for roles before 2019, compressed in Variant A per Content Strategy Section 7.
  t.sort_order                                                                  -- Reverse chronological display order.
FROM job_entries t;

-- ----------------------------------------------------------------------------
-- vw_resume_variants: Table: ResumeVariants. Two variants, one spine, per David_Shadle_Resume_Variants_v1.md. Variant A is public/served from the site; Variant B is sent directly and never published.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_resume_variants CASCADE;
CREATE VIEW vw_resume_variants WITH (security_invoker = ON) AS
SELECT
  t.resume_variant_id,                                                          -- Stored identity, slug form.
  calc_resume_variants_name(t.resume_variant_id) AS name,                       -- Display alias.
  t.label,                                                                      -- Variant label.
  t.audience_description,                                                       -- Who this variant targets and how it is distributed.
  t.summary_text,                                                               -- The opening capability statement ('What I do' / 'Summary'). Paragraph breaks encoded as \n\n.
  t.published_on_site                                                           -- Whether this variant is served from the public site (Section 10: only Variant A).
FROM resume_variants t;

-- ----------------------------------------------------------------------------
-- vw_resume_list_items: Table: ResumeListItems. The Methods and Technical blocks, shared identically by both resume variants, replacing the old comma-separated skills paragraph.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_resume_list_items CASCADE;
CREATE VIEW vw_resume_list_items WITH (security_invoker = ON) AS
SELECT
  t.resume_list_item_id,                                                        -- Stored identity, slug form.
  calc_resume_list_items_name(t.resume_list_item_id) AS name,                   -- Display alias.
  t.category,                                                                   -- 'Methods' or 'Technical'.
  t.label,                                                                      -- The item text as it appears on the resume.
  t.sort_order                                                                  -- Display order within its category.
FROM resume_list_items t;

-- ----------------------------------------------------------------------------
-- vw_education_entries: Table: EducationEntries.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_education_entries CASCADE;
CREATE VIEW vw_education_entries WITH (security_invoker = ON) AS
SELECT
  t.education_entries_id,                                                       -- Primary key (synthesized from the calculated Name — the table's logical key — so it wins over incidental Id-ending attribute fields).
  t.education_entry_id,                                                         -- Stored identity, slug form.
  calc_education_entries_name(t.education_entries_id) AS name,                  -- Display alias.
  t.institution,                                                                -- School name.
  t.degree,                                                                     -- Degree earned.
  t.field_of_study,                                                             -- Major/field.
  t.grad_year                                                                   -- Graduation year.
FROM education_entries t;

