-- ============================================================================
-- CREATE POLICIES - Row Level Security policies
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- ============================================================================

-- Enable RLS on all tables

ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE currently_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE bio_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE how_i_work_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE proof_points ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE resume_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE resume_list_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE education_entries ENABLE ROW LEVEL SECURITY;

-- TODO: Add specific RLS policies based on your security requirements
-- Example:
-- CREATE POLICY "Users can view their own data" ON app_user
--   FOR SELECT USING (auth.uid() = user_id);

