-- ============================================================================
-- UPDATE EFFORTLESS SCHEMA - the derived layer, rebuilt from the rulebook
-- ============================================================================
-- Generated by rulebook-to-postgres. DO NOT EDIT — regenerated every build.
--
-- SAFE IN PRODUCTION. This file never drops a table, never drops a column,
-- and never deletes row data. It brings any database in line with the
-- rulebook that shipped in this same commit.
--
-- Views, calc_*/get_* functions and RLS policies hold NO data: they are a
-- pure function of the rulebook. They are dropped and recreated here rather
-- than migrated. Do NOT hand-write a migration that recreates a view or a
-- calc_* function — re-run this file instead.
--
-- A hand-authored migration is needed ONLY for table/column changes that
-- step 1 below cannot infer, and it should contain nothing else.
-- ============================================================================

BEGIN;
SET timezone = 'UTC';

-- === 1. Additive schema: missing tables and columns ========================
-- CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS only. Never drops.

-- ============================================================================
-- CREATE TABLES (check-add mode) - Idempotent schema, never drops columns
-- ============================================================================
-- GENERATED FILE — DO NOT EDIT. Rewritten by every `effortless build`.
--
-- SOURCE OF TRUTH: effortless-rulebook/effortless-rulebook.json
-- Every table below is defined there. To add a table, a column, or a
-- calculated field, edit the rulebook and rebuild — never this file, and
-- never a *b-customize-*.sql file. A table defined outside the rulebook
-- gets no view, no calculated fields, no RuleSpeak and no Explainer DAG.
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Tables: 13
-- Total Raw Fields: 93
-- ============================================================================

SET timezone = 'UTC';

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- SiteSettings: Singleton table of site-wide facts: contact info, positioning statement, and the undated 'Currently' block. One row.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS site_settings (
  site_setting_id                     TEXT                 PRIMARY KEY          -- Stored identity of the singleton settings row.
);
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS contact_email TEXT;                              -- Primary contact email, shown in the Contact section on Home and Work.
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS contact_phone TEXT;                              -- Contact phone number, as it appears on the resume header.
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS site_domain TEXT;                                -- Canonical site domain.
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS portfolio_company_count TEXT;                    -- Standardized portfolio count string, per Content Strategy Section 6 ('100+' everywhere, never 107 or 111).
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS self_description_line TEXT;                      -- The 'full stack product practitioner' anchor phrase. Per Section 2: say it once, never next to a list.
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS positioning_statement TEXT;                      -- The core positioning paragraph everything else derives from (Content Strategy Section 2).
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS hero_headline TEXT;                              -- The large opening line of the Home hero, first person. First sentence of PositioningStatement, curated separately so the hero can style it distinctly from HeroSubheadline.
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS hero_subheadline TEXT;                           -- The medium-sized second line of the Home hero, directly under HeroHeadline. Second/third sentence of PositioningStatement.
ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS banyan_title TEXT;                               -- Full Banyan title, used everywhere per Section 6: 'Technical Advisor, Product Strategy and UX'.
COMMENT ON TABLE site_settings IS 'Singleton table of site-wide facts: contact info, positioning statement, and the undated ''Currently'' block. One row.';
COMMENT ON COLUMN site_settings.site_setting_id IS 'Stored identity of the singleton settings row.';
COMMENT ON COLUMN site_settings.contact_email IS 'Primary contact email, shown in the Contact section on Home and Work.';
COMMENT ON COLUMN site_settings.contact_phone IS 'Contact phone number, as it appears on the resume header.';
COMMENT ON COLUMN site_settings.site_domain IS 'Canonical site domain.';
COMMENT ON COLUMN site_settings.portfolio_company_count IS 'Standardized portfolio count string, per Content Strategy Section 6 (''100+'' everywhere, never 107 or 111).';
COMMENT ON COLUMN site_settings.self_description_line IS 'The ''full stack product practitioner'' anchor phrase. Per Section 2: say it once, never next to a list.';
COMMENT ON COLUMN site_settings.positioning_statement IS 'The core positioning paragraph everything else derives from (Content Strategy Section 2).';
COMMENT ON COLUMN site_settings.hero_headline IS 'The large opening line of the Home hero, first person. First sentence of PositioningStatement, curated separately so the hero can style it distinctly from HeroSubheadline.';
COMMENT ON COLUMN site_settings.hero_subheadline IS 'The medium-sized second line of the Home hero, directly under HeroHeadline. Second/third sentence of PositioningStatement.';
COMMENT ON COLUMN site_settings.banyan_title IS 'Full Banyan title, used everywhere per Section 6: ''Technical Advisor, Product Strategy and UX''.';

-- ----------------------------------------------------------------------------
-- CurrentlyItems: Table: CurrentlyItems. The undated 'Currently' block on Home (Section 10): a short bulleted list of what David is working on now. Update items when something changes, not on a schedule.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS currently_items (
  currently_item_id                   TEXT                 PRIMARY KEY          -- Stored identity, slug form.
);
ALTER TABLE currently_items ADD COLUMN IF NOT EXISTS title TEXT;                                    -- The bullet's title/name, e.g. 'Banyan Software' or 'Lookout Together'.
ALTER TABLE currently_items ADD COLUMN IF NOT EXISTS body_text TEXT;                                -- The bullet's description text, under the title.
ALTER TABLE currently_items ADD COLUMN IF NOT EXISTS sort_order INTEGER;                            -- Display order.
COMMENT ON TABLE currently_items IS 'Table: CurrentlyItems. The undated ''Currently'' block on Home (Section 10): a short bulleted list of what David is working on now. Update items when something changes, not on a schedule.';
COMMENT ON COLUMN currently_items.currently_item_id IS 'Stored identity, slug form.';
COMMENT ON COLUMN currently_items.title IS 'The bullet''s title/name, e.g. ''Banyan Software'' or ''Lookout Together''.';
COMMENT ON COLUMN currently_items.body_text IS 'The bullet''s description text, under the title.';
COMMENT ON COLUMN currently_items.sort_order IS 'Display order.';

-- ----------------------------------------------------------------------------
-- BioVariants: Table: BioVariants. Five lengths plus one alternate, one spine, per David_Shadle_Bio_Set_v1.md. Voice standard applied: no em dashes, short sentences, active voice, no filler.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bio_variants (
  bio_variant_id                      TEXT                 PRIMARY KEY          -- Stored identity, slug form.
);
ALTER TABLE bio_variants ADD COLUMN IF NOT EXISTS label TEXT;                                       -- Human label for this bio length/context, e.g. 'Fifty words'.
ALTER TABLE bio_variants ADD COLUMN IF NOT EXISTS usage_context TEXT;                               -- Where this variant gets used, e.g. 'Directory listings, conference programs, deck footers, introductions.'
ALTER TABLE bio_variants ADD COLUMN IF NOT EXISTS body_text TEXT;                                   -- The bio copy itself. Paragraph breaks encoded as \n\n.
ALTER TABLE bio_variants ADD COLUMN IF NOT EXISTS sort_order INTEGER;                               -- Display order, shortest to longest.
COMMENT ON TABLE bio_variants IS 'Table: BioVariants. Five lengths plus one alternate, one spine, per David_Shadle_Bio_Set_v1.md. Voice standard applied: no em dashes, short sentences, active voice, no filler.';
COMMENT ON COLUMN bio_variants.bio_variant_id IS 'Stored identity, slug form.';
COMMENT ON COLUMN bio_variants.label IS 'Human label for this bio length/context, e.g. ''Fifty words''.';
COMMENT ON COLUMN bio_variants.usage_context IS 'Where this variant gets used, e.g. ''Directory listings, conference programs, deck footers, introductions.''';
COMMENT ON COLUMN bio_variants.body_text IS 'The bio copy itself. Paragraph breaks encoded as \n\n.';
COMMENT ON COLUMN bio_variants.sort_order IS 'Display order, shortest to longest.';

-- ----------------------------------------------------------------------------
-- HowIWorkSections: Table: HowIWorkSections. The method statement for the How I Work page, per David_Shadle_How_I_Work_v1.md. Written to be true indefinitely.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS how_i_work_sections (
  how_i_work_section_id               TEXT                 PRIMARY KEY          -- Stored identity, slug form.
);
ALTER TABLE how_i_work_sections ADD COLUMN IF NOT EXISTS heading TEXT;                              -- Section heading as it appears on the page.
ALTER TABLE how_i_work_sections ADD COLUMN IF NOT EXISTS body_text TEXT;                            -- Full-page body copy for this section. Paragraph breaks encoded as \n\n.
ALTER TABLE how_i_work_sections ADD COLUMN IF NOT EXISTS short_body_text TEXT;                      -- Condensed ~1-paragraph version, used if How I Work becomes a Home section instead of its own page. Null where the short version drops the section entirely.
ALTER TABLE how_i_work_sections ADD COLUMN IF NOT EXISTS sort_order INTEGER;                        -- Display order on the page.
COMMENT ON TABLE how_i_work_sections IS 'Table: HowIWorkSections. The method statement for the How I Work page, per David_Shadle_How_I_Work_v1.md. Written to be true indefinitely.';
COMMENT ON COLUMN how_i_work_sections.how_i_work_section_id IS 'Stored identity, slug form.';
COMMENT ON COLUMN how_i_work_sections.heading IS 'Section heading as it appears on the page.';
COMMENT ON COLUMN how_i_work_sections.body_text IS 'Full-page body copy for this section. Paragraph breaks encoded as \n\n.';
COMMENT ON COLUMN how_i_work_sections.short_body_text IS 'Condensed ~1-paragraph version, used if How I Work becomes a Home section instead of its own page. Null where the short version drops the section entirely.';
COMMENT ON COLUMN how_i_work_sections.sort_order IS 'Display order on the page.';

-- ----------------------------------------------------------------------------
-- ProofPoints: Table: ProofPoints. The proof inventory from Content Strategy Section 4. Raw material for the Work page and the resume's Selected Work block. Nothing goes into a bio, resume, or Work page entry that is not traceable to a row here.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS proof_points (
  proof_point_id                      TEXT                 PRIMARY KEY          -- Stored identity, slug form, matches Content Strategy subsection (e.g. 'pm-portal' for 4.2).
);
ALTER TABLE proof_points ADD COLUMN IF NOT EXISTS title TEXT;                                       -- Short title for this proof point.
ALTER TABLE proof_points ADD COLUMN IF NOT EXISTS problem_text TEXT;                                -- The problem, as stated in the proof inventory.
ALTER TABLE proof_points ADD COLUMN IF NOT EXISTS action_text TEXT;                                 -- The action taken.
ALTER TABLE proof_points ADD COLUMN IF NOT EXISTS outcome_text TEXT;                                -- The outcome.
ALTER TABLE proof_points ADD COLUMN IF NOT EXISTS attribution_note TEXT;                            -- Precise attribution language required when describing this work (e.g. 'advised on and implemented,' not 'owned'). See Content Strategy Section 6.
ALTER TABLE proof_points ADD COLUMN IF NOT EXISTS register_note TEXT;                               -- Internal guidance on tone/register for this proof point. Not published copy - for whoever writes site/resume text from this row.
ALTER TABLE proof_points ADD COLUMN IF NOT EXISTS client_or_category TEXT;                          -- Client name where nameable, otherwise a category label (e.g. 'Medical technology'). Shown as the first half of the Projects page meta row.
ALTER TABLE proof_points ADD COLUMN IF NOT EXISTS status_label TEXT;                                -- Short status/type word for the Projects page meta row (e.g. 'Live in production', 'Problem brief').
ALTER TABLE proof_points ADD COLUMN IF NOT EXISTS featured_on_work_page BOOLEAN;                    -- Whether this proof point is one of the 2-3 engagements shown on the Work page (Section 10). First-pass selection - confirm with David before Phase 2.
ALTER TABLE proof_points ADD COLUMN IF NOT EXISTS featured_in_resume_selected_work BOOLEAN;         -- Whether this proof point appears in the resume's 'Selected work, 2024 to 2026' block (Variant A).
ALTER TABLE proof_points ADD COLUMN IF NOT EXISTS image_url TEXT;                                   -- Public URL of this project's single representative image (hosted in Cloudflare R2). Optional — shown on the Work page when set.
ALTER TABLE proof_points ADD COLUMN IF NOT EXISTS sort_order INTEGER;                               -- Order matching Content Strategy Section 4 numbering.
COMMENT ON TABLE proof_points IS 'Table: ProofPoints. The proof inventory from Content Strategy Section 4. Raw material for the Work page and the resume''s Selected Work block. Nothing goes into a bio, resume, or Work page entry that is not traceable to a row here.';
COMMENT ON COLUMN proof_points.proof_point_id IS 'Stored identity, slug form, matches Content Strategy subsection (e.g. ''pm-portal'' for 4.2).';
COMMENT ON COLUMN proof_points.title IS 'Short title for this proof point.';
COMMENT ON COLUMN proof_points.problem_text IS 'The problem, as stated in the proof inventory.';
COMMENT ON COLUMN proof_points.action_text IS 'The action taken.';
COMMENT ON COLUMN proof_points.outcome_text IS 'The outcome.';
COMMENT ON COLUMN proof_points.attribution_note IS 'Precise attribution language required when describing this work (e.g. ''advised on and implemented,'' not ''owned''). See Content Strategy Section 6.';
COMMENT ON COLUMN proof_points.register_note IS 'Internal guidance on tone/register for this proof point. Not published copy - for whoever writes site/resume text from this row.';
COMMENT ON COLUMN proof_points.client_or_category IS 'Client name where nameable, otherwise a category label (e.g. ''Medical technology''). Shown as the first half of the Projects page meta row.';
COMMENT ON COLUMN proof_points.status_label IS 'Short status/type word for the Projects page meta row (e.g. ''Live in production'', ''Problem brief'').';
COMMENT ON COLUMN proof_points.featured_on_work_page IS 'Whether this proof point is one of the 2-3 engagements shown on the Work page (Section 10). First-pass selection - confirm with David before Phase 2.';
COMMENT ON COLUMN proof_points.featured_in_resume_selected_work IS 'Whether this proof point appears in the resume''s ''Selected work, 2024 to 2026'' block (Variant A).';
COMMENT ON COLUMN proof_points.image_url IS 'Public URL of this project''s single representative image (hosted in Cloudflare R2). Optional — shown on the Work page when set.';
COMMENT ON COLUMN proof_points.sort_order IS 'Order matching Content Strategy Section 4 numbering.';

-- ----------------------------------------------------------------------------
-- JobEntries: Table: JobEntries. Career history, shared by both resume variants via inclusion flags rather than duplicated per variant. Rows are grouped by DisplayGroupKey where a variant collapses multiple rows into one displayed entry (e.g. Variant A merges the two Power Automate roles).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS job_entries (
  job_entry_id                        TEXT                 PRIMARY KEY          -- Stored identity, slug form.
);
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS company TEXT;                                      -- Employer or entity name.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS job_title TEXT;                                    -- Title held. Null on the single synthetic 'earlier roles' compressed row.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS start_date DATE;                                   -- Start, YYYY-MM.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS end_date DATE;                                     -- End, YYYY-MM. Null if current.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS is_current BOOLEAN;                                -- True if this role is ongoing.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS display_group_key TEXT;                            -- Rows sharing this key render as one entry in Variant A (which uses the coarser grouping). Null where no grouping applies.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS summary_text_variant_a TEXT;                       -- Prose summary as it appears in Resume Variant A. On a grouped pair, only the earliest row in the group carries the merged text; the later row is null and the app renders the group using the earliest row's text with the group's full date range.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS summary_text_variant_b TEXT;                       -- Bullet-point summary as it appears in Resume Variant B, bullets joined with \n.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS compressed_line TEXT;                              -- One-line compressed text, used only on the synthetic 'earlier roles' row for Variant A's single-line pre-2019 summary.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS include_in_variant_a BOOLEAN;                      -- Whether this row is shown (individually or as part of a group) on Resume Variant A.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS include_in_variant_b BOOLEAN;                      -- Whether this row is shown on Resume Variant B.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS is_pre2019 BOOLEAN;                                -- True for roles before 2019, compressed in Variant A per Content Strategy Section 7.
ALTER TABLE job_entries ADD COLUMN IF NOT EXISTS sort_order INTEGER;                                -- Reverse chronological display order.
COMMENT ON TABLE job_entries IS 'Table: JobEntries. Career history, shared by both resume variants via inclusion flags rather than duplicated per variant. Rows are grouped by DisplayGroupKey where a variant collapses multiple rows into one displayed entry (e.g. Variant A merges the two Power Automate roles).';
COMMENT ON COLUMN job_entries.job_entry_id IS 'Stored identity, slug form.';
COMMENT ON COLUMN job_entries.company IS 'Employer or entity name.';
COMMENT ON COLUMN job_entries.job_title IS 'Title held. Null on the single synthetic ''earlier roles'' compressed row.';
COMMENT ON COLUMN job_entries.start_date IS 'Start, YYYY-MM.';
COMMENT ON COLUMN job_entries.end_date IS 'End, YYYY-MM. Null if current.';
COMMENT ON COLUMN job_entries.is_current IS 'True if this role is ongoing.';
COMMENT ON COLUMN job_entries.display_group_key IS 'Rows sharing this key render as one entry in Variant A (which uses the coarser grouping). Null where no grouping applies.';
COMMENT ON COLUMN job_entries.summary_text_variant_a IS 'Prose summary as it appears in Resume Variant A. On a grouped pair, only the earliest row in the group carries the merged text; the later row is null and the app renders the group using the earliest row''s text with the group''s full date range.';
COMMENT ON COLUMN job_entries.summary_text_variant_b IS 'Bullet-point summary as it appears in Resume Variant B, bullets joined with \n.';
COMMENT ON COLUMN job_entries.compressed_line IS 'One-line compressed text, used only on the synthetic ''earlier roles'' row for Variant A''s single-line pre-2019 summary.';
COMMENT ON COLUMN job_entries.include_in_variant_a IS 'Whether this row is shown (individually or as part of a group) on Resume Variant A.';
COMMENT ON COLUMN job_entries.include_in_variant_b IS 'Whether this row is shown on Resume Variant B.';
COMMENT ON COLUMN job_entries.is_pre2019 IS 'True for roles before 2019, compressed in Variant A per Content Strategy Section 7.';
COMMENT ON COLUMN job_entries.sort_order IS 'Reverse chronological display order.';

-- ----------------------------------------------------------------------------
-- ResumeVariants: Table: ResumeVariants. Two variants, one spine, per David_Shadle_Resume_Variants_v1.md. Variant A is public/served from the site; Variant B is sent directly and never published.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS resume_variants (
  resume_variant_id                   TEXT                 PRIMARY KEY          -- Stored identity, slug form.
);
ALTER TABLE resume_variants ADD COLUMN IF NOT EXISTS label TEXT;                                    -- Variant label.
ALTER TABLE resume_variants ADD COLUMN IF NOT EXISTS audience_description TEXT;                     -- Who this variant targets and how it is distributed.
ALTER TABLE resume_variants ADD COLUMN IF NOT EXISTS summary_text TEXT;                             -- The opening capability statement ('What I do' / 'Summary'). Paragraph breaks encoded as \n\n.
ALTER TABLE resume_variants ADD COLUMN IF NOT EXISTS published_on_site BOOLEAN;                     -- Whether this variant is served from the public site (Section 10: only Variant A).
COMMENT ON TABLE resume_variants IS 'Table: ResumeVariants. Two variants, one spine, per David_Shadle_Resume_Variants_v1.md. Variant A is public/served from the site; Variant B is sent directly and never published.';
COMMENT ON COLUMN resume_variants.resume_variant_id IS 'Stored identity, slug form.';
COMMENT ON COLUMN resume_variants.label IS 'Variant label.';
COMMENT ON COLUMN resume_variants.audience_description IS 'Who this variant targets and how it is distributed.';
COMMENT ON COLUMN resume_variants.summary_text IS 'The opening capability statement (''What I do'' / ''Summary''). Paragraph breaks encoded as \n\n.';
COMMENT ON COLUMN resume_variants.published_on_site IS 'Whether this variant is served from the public site (Section 10: only Variant A).';

-- ----------------------------------------------------------------------------
-- ResumeListItems: Table: ResumeListItems. The Methods and Technical blocks, shared identically by both resume variants, replacing the old comma-separated skills paragraph.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS resume_list_items (
  resume_list_item_id                 TEXT                 PRIMARY KEY          -- Stored identity, slug form.
);
ALTER TABLE resume_list_items ADD COLUMN IF NOT EXISTS category TEXT;                               -- 'Methods' or 'Technical'.
ALTER TABLE resume_list_items ADD COLUMN IF NOT EXISTS label TEXT;                                  -- The item text as it appears on the resume.
ALTER TABLE resume_list_items ADD COLUMN IF NOT EXISTS sort_order INTEGER;                          -- Display order within its category.
COMMENT ON TABLE resume_list_items IS 'Table: ResumeListItems. The Methods and Technical blocks, shared identically by both resume variants, replacing the old comma-separated skills paragraph.';
COMMENT ON COLUMN resume_list_items.resume_list_item_id IS 'Stored identity, slug form.';
COMMENT ON COLUMN resume_list_items.category IS '''Methods'' or ''Technical''.';
COMMENT ON COLUMN resume_list_items.label IS 'The item text as it appears on the resume.';
COMMENT ON COLUMN resume_list_items.sort_order IS 'Display order within its category.';

-- ----------------------------------------------------------------------------
-- EducationEntries: Table: EducationEntries.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS education_entries (
  education_entry_id                  TEXT                 PRIMARY KEY          -- Stored identity, slug form.
);
ALTER TABLE education_entries ADD COLUMN IF NOT EXISTS institution TEXT;                            -- School name.
ALTER TABLE education_entries ADD COLUMN IF NOT EXISTS degree TEXT;                                 -- Degree earned.
ALTER TABLE education_entries ADD COLUMN IF NOT EXISTS field_of_study TEXT;                         -- Major/field.
ALTER TABLE education_entries ADD COLUMN IF NOT EXISTS grad_year INTEGER;                           -- Graduation year.
COMMENT ON TABLE education_entries IS 'Table: EducationEntries.';
COMMENT ON COLUMN education_entries.education_entry_id IS 'Stored identity, slug form.';
COMMENT ON COLUMN education_entries.institution IS 'School name.';
COMMENT ON COLUMN education_entries.degree IS 'Degree earned.';
COMMENT ON COLUMN education_entries.field_of_study IS 'Major/field.';
COMMENT ON COLUMN education_entries.grad_year IS 'Graduation year.';

-- ----------------------------------------------------------------------------
-- LandingPages: Table: LandingPages. One promotional landing page per row, reachable only by its direct URL. LandingPageId is the URL slug.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS landing_pages (
  landing_page_id                     TEXT                 PRIMARY KEY          -- Stored identity. The URL slug, for example idea-to-evidence.
);
ALTER TABLE landing_pages ADD COLUMN IF NOT EXISTS meta_title TEXT;                                 -- Browser title and Open Graph title.
ALTER TABLE landing_pages ADD COLUMN IF NOT EXISTS meta_description TEXT;                           -- Meta description and Open Graph description.
ALTER TABLE landing_pages ADD COLUMN IF NOT EXISTS eyebrow TEXT;                                    -- Small label above the headline in the hero.
ALTER TABLE landing_pages ADD COLUMN IF NOT EXISTS headline TEXT;                                   -- The page h1.
ALTER TABLE landing_pages ADD COLUMN IF NOT EXISTS lede TEXT;                                       -- Opening paragraph under the headline.
ALTER TABLE landing_pages ADD COLUMN IF NOT EXISTS video_url TEXT;                                  -- Optional YouTube link. When present, the video is shown in the hero between the eyebrow and the headline.
ALTER TABLE landing_pages ADD COLUMN IF NOT EXISTS primary_cta_label TEXT;                          -- Label of the primary call-to-action button.
ALTER TABLE landing_pages ADD COLUMN IF NOT EXISTS primary_cta_href TEXT;                           -- Target of the primary call-to-action button (mailto: or path).
ALTER TABLE landing_pages ADD COLUMN IF NOT EXISTS secondary_cta_label TEXT;                        -- Label of the optional secondary button.
ALTER TABLE landing_pages ADD COLUMN IF NOT EXISTS secondary_cta_href TEXT;                         -- Target of the optional secondary button.
ALTER TABLE landing_pages ADD COLUMN IF NOT EXISTS is_published BOOLEAN;                            -- Whether the page is served. Unpublished pages return 404.
COMMENT ON TABLE landing_pages IS 'Table: LandingPages. One promotional landing page per row, reachable only by its direct URL. LandingPageId is the URL slug.';
COMMENT ON COLUMN landing_pages.landing_page_id IS 'Stored identity. The URL slug, for example idea-to-evidence.';
COMMENT ON COLUMN landing_pages.meta_title IS 'Browser title and Open Graph title.';
COMMENT ON COLUMN landing_pages.meta_description IS 'Meta description and Open Graph description.';
COMMENT ON COLUMN landing_pages.eyebrow IS 'Small label above the headline in the hero.';
COMMENT ON COLUMN landing_pages.headline IS 'The page h1.';
COMMENT ON COLUMN landing_pages.lede IS 'Opening paragraph under the headline.';
COMMENT ON COLUMN landing_pages.video_url IS 'Optional YouTube link. When present, the video is shown in the hero between the eyebrow and the headline.';
COMMENT ON COLUMN landing_pages.primary_cta_label IS 'Label of the primary call-to-action button.';
COMMENT ON COLUMN landing_pages.primary_cta_href IS 'Target of the primary call-to-action button (mailto: or path).';
COMMENT ON COLUMN landing_pages.secondary_cta_label IS 'Label of the optional secondary button.';
COMMENT ON COLUMN landing_pages.secondary_cta_href IS 'Target of the optional secondary button.';
COMMENT ON COLUMN landing_pages.is_published IS 'Whether the page is served. Unpublished pages return 404.';

-- ----------------------------------------------------------------------------
-- LandingPageSections: Table: LandingPageSections. The ordered sections of a landing page. Kind selects the renderer.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS landing_page_sections (
  landing_page_section_id             TEXT                 PRIMARY KEY          -- Stored identity, slug form.
);
ALTER TABLE landing_page_sections ADD COLUMN IF NOT EXISTS landing_page TEXT;                       -- The landing page this section belongs to.
ALTER TABLE landing_page_sections ADD COLUMN IF NOT EXISTS sort_order INTEGER;                      -- Display order within the page.
ALTER TABLE landing_page_sections ADD COLUMN IF NOT EXISTS kind TEXT;                               -- Renderer: prose, list, steps, cards or callout.
ALTER TABLE landing_page_sections ADD COLUMN IF NOT EXISTS anchor_id TEXT;                          -- Optional HTML id for the section, for in-page links.
ALTER TABLE landing_page_sections ADD COLUMN IF NOT EXISTS eyebrow TEXT;                            -- Small label above the section heading.
ALTER TABLE landing_page_sections ADD COLUMN IF NOT EXISTS heading TEXT;                            -- Section heading.
ALTER TABLE landing_page_sections ADD COLUMN IF NOT EXISTS body_text TEXT;                          -- Section body copy. Paragraph breaks encoded as \n\n.
COMMENT ON TABLE landing_page_sections IS 'Table: LandingPageSections. The ordered sections of a landing page. Kind selects the renderer.';
COMMENT ON COLUMN landing_page_sections.landing_page_section_id IS 'Stored identity, slug form.';
COMMENT ON COLUMN landing_page_sections.landing_page IS 'The landing page this section belongs to.';
COMMENT ON COLUMN landing_page_sections.sort_order IS 'Display order within the page.';
COMMENT ON COLUMN landing_page_sections.kind IS 'Renderer: prose, list, steps, cards or callout.';
COMMENT ON COLUMN landing_page_sections.anchor_id IS 'Optional HTML id for the section, for in-page links.';
COMMENT ON COLUMN landing_page_sections.eyebrow IS 'Small label above the section heading.';
COMMENT ON COLUMN landing_page_sections.heading IS 'Section heading.';
COMMENT ON COLUMN landing_page_sections.body_text IS 'Section body copy. Paragraph breaks encoded as \n\n.';

-- ----------------------------------------------------------------------------
-- LandingPageItems: Table: LandingPageItems. The ordered items inside a landing page section (cards, steps, list entries).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS landing_page_items (
  landing_page_item_id                TEXT                 PRIMARY KEY          -- Stored identity, slug form.
);
ALTER TABLE landing_page_items ADD COLUMN IF NOT EXISTS landing_page_section TEXT;                  -- The section this item belongs to.
ALTER TABLE landing_page_items ADD COLUMN IF NOT EXISTS sort_order INTEGER;                         -- Display order within the section.
ALTER TABLE landing_page_items ADD COLUMN IF NOT EXISTS label TEXT;                                 -- Optional short marker, for example a step number.
ALTER TABLE landing_page_items ADD COLUMN IF NOT EXISTS heading TEXT;                               -- Item heading.
ALTER TABLE landing_page_items ADD COLUMN IF NOT EXISTS body_text TEXT;                             -- Item body copy.
COMMENT ON TABLE landing_page_items IS 'Table: LandingPageItems. The ordered items inside a landing page section (cards, steps, list entries).';
COMMENT ON COLUMN landing_page_items.landing_page_item_id IS 'Stored identity, slug form.';
COMMENT ON COLUMN landing_page_items.landing_page_section IS 'The section this item belongs to.';
COMMENT ON COLUMN landing_page_items.sort_order IS 'Display order within the section.';
COMMENT ON COLUMN landing_page_items.label IS 'Optional short marker, for example a step number.';
COMMENT ON COLUMN landing_page_items.heading IS 'Item heading.';
COMMENT ON COLUMN landing_page_items.body_text IS 'Item body copy.';

-- ----------------------------------------------------------------------------
-- LandingPageItemFacts: Table: LandingPageItemFacts. Labeled lines shown under a landing page item.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS landing_page_item_facts (
  landing_page_item_fact_id           TEXT                 PRIMARY KEY          -- Stored identity, slug form.
);
ALTER TABLE landing_page_item_facts ADD COLUMN IF NOT EXISTS landing_page_item TEXT;                -- The item this fact belongs to.
ALTER TABLE landing_page_item_facts ADD COLUMN IF NOT EXISTS sort_order INTEGER;                    -- Display order within the item.
ALTER TABLE landing_page_item_facts ADD COLUMN IF NOT EXISTS label TEXT;                            -- Fact label, for example What happens.
ALTER TABLE landing_page_item_facts ADD COLUMN IF NOT EXISTS body_text TEXT;                        -- Fact text. One fact per line when it is a list.
COMMENT ON TABLE landing_page_item_facts IS 'Table: LandingPageItemFacts. Labeled lines shown under a landing page item.';
COMMENT ON COLUMN landing_page_item_facts.landing_page_item_fact_id IS 'Stored identity, slug form.';
COMMENT ON COLUMN landing_page_item_facts.landing_page_item IS 'The item this fact belongs to.';
COMMENT ON COLUMN landing_page_item_facts.sort_order IS 'Display order within the item.';
COMMENT ON COLUMN landing_page_item_facts.label IS 'Fact label, for example What happens.';
COMMENT ON COLUMN landing_page_item_facts.body_text IS 'Fact text. One fact per line when it is a list.';

-- ============================================================================
-- FK INDEXES - Performance only, always applied
-- ============================================================================

-- LandingPageSections
CREATE INDEX IF NOT EXISTS idx_landing_page_sections_landing_page ON landing_page_sections (landing_page);

-- LandingPageItems
CREATE INDEX IF NOT EXISTS idx_landing_page_items_landing_page_section ON landing_page_items (landing_page_section);

-- LandingPageItemFacts
CREATE INDEX IF NOT EXISTS idx_landing_page_item_facts_landing_page_item ON landing_page_item_facts (landing_page_item);

-- 3 FK index(es) declared.


-- === 2/3. Drop the derived layer ==========================================
-- Views first (they depend on functions), then functions leaf-up through the
-- DAG. CASCADE handles the dependency order Postgres knows about; the
-- explicit ordering handles calc_* functions that call other calc_*.
DO $drop_derived$
DECLARE r RECORD; v_views INT := 0; v_fns INT := 0;
BEGIN
    -- 2. Views (depend on functions, so they go first).
    FOR r IN (
        SELECT table_name FROM information_schema.views
         WHERE table_schema = 'public' AND table_name LIKE 'vw\_%'
           AND obj_description(
                 (quote_ident(table_schema) || '.' || quote_ident(table_name))::regclass, 'pg_class')
               IS DISTINCT FROM 'effortless:hand-maintained'
    ) LOOP
        EXECUTE 'DROP VIEW IF EXISTS public.' || quote_ident(r.table_name) || ' CASCADE';
        v_views := v_views + 1;
    END LOOP;

    -- 3. Functions, leaf-up through the DAG. A calc_* may call another
    --    calc_*, so depth-ordering avoids dependency errors.
    FOR r IN (
        WITH fn AS (
            SELECT p.oid, p.proname,
                   pg_get_function_identity_arguments(p.oid) AS args,
                   p.prosrc
              FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
             WHERE n.nspname = 'public'
               AND (p.proname LIKE 'calc\_%' OR p.proname LIKE 'get\_%')
               AND COALESCE(obj_description(p.oid, 'pg_proc'), '')
                   IS DISTINCT FROM 'effortless:hand-maintained'
        )
        -- callers before callees: a function whose body names another
        -- generated function is an interior node and must go first.
        SELECT f.proname, f.args,
               (SELECT count(*) FROM fn c
                 WHERE c.oid <> f.oid AND f.prosrc LIKE '%' || c.proname || '%') AS depth
          FROM fn f
         ORDER BY depth DESC, f.proname
    ) LOOP
        EXECUTE 'DROP FUNCTION IF EXISTS public.' || quote_ident(r.proname)
                || '(' || r.args || ') CASCADE';
        v_fns := v_fns + 1;
    END LOOP;

    RAISE NOTICE 'derived layer dropped: % views, % functions', v_views, v_fns;
END
$drop_derived$;


-- === 4. Static reference data =============================================
-- (no tables marked IsStatic — nothing to upsert)

-- === 5. Recreate calc_*/get_* functions ===================================
-- ============================================================================
-- CREATE FUNCTIONS - Calculation functions for lookup/calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- ============================================================================


-- Disable body validation so LANGUAGE sql functions can forward-reference
-- each other within this file. (pg_dump does the same thing for the same
-- reason.) Without this, SQL functions parse-check at CREATE time and fail
-- on the first forward call site; plpgsql didn't, which is how this file
-- ever worked. Dependency order is still enforced at EXECUTION time.
SET check_function_bodies = off;

-- ============================================================================
-- ERB BUILD PARAMETERS (docs/ERB-BUILD-PARAMETERS.md)
-- erbBlankLogic=coerce, erbDateDiff=calendar, erbDateTimeText=iso8601, erbTimezone=UTC, erbWholeNumber=by-field-type
-- ============================================================================

CREATE OR REPLACE FUNCTION erb_build_parameters()
RETURNS JSONB AS $$
  SELECT '{"erbBlankLogic":"coerce","erbDateDiff":"calendar","erbDateTimeText":"iso8601","erbTimezone":"UTC","erbWholeNumber":"by-field-type"}'::jsonb;
$$ LANGUAGE sql IMMUTABLE;

-- A timestamp inside text, per erbDateTimeText, in erbTimezone. Blank renders ''.
CREATE OR REPLACE FUNCTION erb_datetime_text(ts TIMESTAMPTZ)
RETURNS TEXT AS $$
  SELECT CASE WHEN ts IS NULL THEN '' ELSE
    to_char(ts AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS')
    || CASE WHEN (EXTRACT(MICROSECONDS FROM ts)::bigint % 1000000) <> 0 THEN rtrim(to_char(ts AT TIME ZONE 'UTC', '.US'), '0') ELSE '' END
    || CASE WHEN o.off < 0 THEN '-' ELSE '+' END || lpad((abs(o.off) / 3600)::text, 2, '0') || ':' || lpad(((abs(o.off) % 3600) / 60)::text, 2, '0')
  END
  FROM (SELECT EXTRACT(EPOCH FROM ((ts AT TIME ZONE 'UTC') - (ts AT TIME ZONE 'UTC')))::integer AS off) o;
$$ LANGUAGE sql STABLE;

-- A date inside text: YYYY-MM-DD. Blank renders ''.
CREATE OR REPLACE FUNCTION erb_date_text(d DATE)
RETURNS TEXT AS $$
  SELECT COALESCE(to_char(d, 'YYYY-MM-DD'), '');
$$ LANGUAGE sql IMMUTABLE;

-- A number inside text: the shortest exact form, no trailing .0 (2, 2.5). Blank renders ''.
CREATE OR REPLACE FUNCTION erb_number_text(n NUMERIC)
RETURNS TEXT AS $$
  SELECT CASE WHEN n IS NULL THEN ''
              WHEN n::text LIKE '%.%' THEN rtrim(rtrim(n::text, '0'), '.')
              ELSE n::text END;
$$ LANGUAGE sql IMMUTABLE;


-- ============================================================================
-- LOOKUP FUNCTIONS
-- These functions perform lookups via foreign key relationships
-- ============================================================================

-- calc_site_settings_name
-- Field: SiteSettings.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_site_settings_name(p_site_setting_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(site_setting_id, '') FROM site_settings WHERE site_setting_id = p_site_setting_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_currently_items_name
-- Field: CurrentlyItems.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_currently_items_name(p_currently_item_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(title, '') FROM currently_items WHERE currently_item_id = p_currently_item_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_bio_variants_name
-- Field: BioVariants.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_bio_variants_name(p_bio_variant_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(label, '') FROM bio_variants WHERE bio_variant_id = p_bio_variant_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_how_i_work_sections_name
-- Field: HowIWorkSections.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_how_i_work_sections_name(p_how_i_work_section_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(heading, '') FROM how_i_work_sections WHERE how_i_work_section_id = p_how_i_work_section_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_proof_points_name
-- Field: ProofPoints.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_proof_points_name(p_proof_point_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(title, '') FROM proof_points WHERE proof_point_id = p_proof_point_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_job_entries_name
-- Field: JobEntries.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_job_entries_name(p_job_entry_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(company, '') FROM job_entries WHERE job_entry_id = p_job_entry_id), ' - ', (SELECT NULLIF(job_title, '') FROM job_entries WHERE job_entry_id = p_job_entry_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_resume_variants_name
-- Field: ResumeVariants.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_resume_variants_name(p_resume_variant_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(label, '') FROM resume_variants WHERE resume_variant_id = p_resume_variant_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_resume_list_items_name
-- Field: ResumeListItems.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_resume_list_items_name(p_resume_list_item_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(label, '') FROM resume_list_items WHERE resume_list_item_id = p_resume_list_item_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_education_entries_name
-- Field: EducationEntries.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_education_entries_name(p_education_entry_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(institution, '') FROM education_entries WHERE education_entry_id = p_education_entry_id), ' - ', (SELECT NULLIF(degree, '') FROM education_entries WHERE education_entry_id = p_education_entry_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_landing_pages_name
-- Field: LandingPages.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_landing_pages_name(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(headline, '') FROM landing_pages WHERE landing_page_id = p_landing_page_id))::text;
$$ LANGUAGE sql STABLE;

-- get_landing_pages_meta_title
-- Helper function: Get MetaTitle from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_meta_title(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT meta_title FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- get_landing_pages_meta_description
-- Helper function: Get MetaDescription from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_meta_description(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT meta_description FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- get_landing_pages_eyebrow
-- Helper function: Get Eyebrow from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_eyebrow(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT eyebrow FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- get_landing_pages_headline
-- Helper function: Get Headline from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_headline(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT headline FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- get_landing_pages_lede
-- Helper function: Get Lede from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_lede(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT lede FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- get_landing_pages_video_url
-- Helper function: Get VideoUrl from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_video_url(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT video_url FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- get_landing_pages_primary_cta_label
-- Helper function: Get PrimaryCtaLabel from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_primary_cta_label(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT primary_cta_label FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- get_landing_pages_primary_cta_href
-- Helper function: Get PrimaryCtaHref from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_primary_cta_href(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT primary_cta_href FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- get_landing_pages_secondary_cta_label
-- Helper function: Get SecondaryCtaLabel from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_secondary_cta_label(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT secondary_cta_label FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- get_landing_pages_secondary_cta_href
-- Helper function: Get SecondaryCtaHref from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_secondary_cta_href(p_landing_page_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT secondary_cta_href FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- get_landing_pages_is_published
-- Helper function: Get IsPublished from LandingPages by LandingPageId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_pages_is_published(p_landing_page_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT is_published FROM landing_pages WHERE landing_page_id = p_landing_page_id);
$$ LANGUAGE sql STABLE;

-- calc_landing_page_sections_name
-- Field: LandingPageSections.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_landing_page_sections_name(p_landing_page_section_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(heading, '') FROM landing_page_sections WHERE landing_page_section_id = p_landing_page_section_id))::text;
$$ LANGUAGE sql STABLE;

-- get_landing_page_sections_sort_order
-- Helper function: Get SortOrder from LandingPageSections by LandingPageSectionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_page_sections_sort_order(p_landing_page_section_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT sort_order FROM landing_page_sections WHERE landing_page_section_id = p_landing_page_section_id);
$$ LANGUAGE sql STABLE;

-- get_landing_page_sections_kind
-- Helper function: Get Kind from LandingPageSections by LandingPageSectionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_page_sections_kind(p_landing_page_section_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT kind FROM landing_page_sections WHERE landing_page_section_id = p_landing_page_section_id);
$$ LANGUAGE sql STABLE;

-- get_landing_page_sections_eyebrow
-- Helper function: Get Eyebrow from LandingPageSections by LandingPageSectionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_page_sections_eyebrow(p_landing_page_section_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT eyebrow FROM landing_page_sections WHERE landing_page_section_id = p_landing_page_section_id);
$$ LANGUAGE sql STABLE;

-- get_landing_page_sections_heading
-- Helper function: Get Heading from LandingPageSections by LandingPageSectionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_page_sections_heading(p_landing_page_section_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT heading FROM landing_page_sections WHERE landing_page_section_id = p_landing_page_section_id);
$$ LANGUAGE sql STABLE;

-- get_landing_page_sections_body_text
-- Helper function: Get BodyText from LandingPageSections by LandingPageSectionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_page_sections_body_text(p_landing_page_section_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT body_text FROM landing_page_sections WHERE landing_page_section_id = p_landing_page_section_id);
$$ LANGUAGE sql STABLE;

-- calc_landing_page_items_name
-- Field: LandingPageItems.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_landing_page_items_name(p_landing_page_item_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(heading, '') FROM landing_page_items WHERE landing_page_item_id = p_landing_page_item_id))::text;
$$ LANGUAGE sql STABLE;

-- get_landing_page_items_sort_order
-- Helper function: Get SortOrder from LandingPageItems by LandingPageItemId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_page_items_sort_order(p_landing_page_item_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT sort_order FROM landing_page_items WHERE landing_page_item_id = p_landing_page_item_id);
$$ LANGUAGE sql STABLE;

-- get_landing_page_items_label
-- Helper function: Get Label from LandingPageItems by LandingPageItemId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_page_items_label(p_landing_page_item_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT label FROM landing_page_items WHERE landing_page_item_id = p_landing_page_item_id);
$$ LANGUAGE sql STABLE;

-- get_landing_page_items_heading
-- Helper function: Get Heading from LandingPageItems by LandingPageItemId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_page_items_heading(p_landing_page_item_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT heading FROM landing_page_items WHERE landing_page_item_id = p_landing_page_item_id);
$$ LANGUAGE sql STABLE;

-- get_landing_page_items_body_text
-- Helper function: Get BodyText from LandingPageItems by LandingPageItemId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_landing_page_items_body_text(p_landing_page_item_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT body_text FROM landing_page_items WHERE landing_page_item_id = p_landing_page_item_id);
$$ LANGUAGE sql STABLE;

-- calc_landing_page_item_facts_name
-- Field: LandingPageItemFacts.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_landing_page_item_facts_name(p_landing_page_item_fact_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(label, '') FROM landing_page_item_facts WHERE landing_page_item_fact_id = p_landing_page_item_fact_id))::text;
$$ LANGUAGE sql STABLE;

-- ============================================================================
-- MANY-SIDE RELATIONSHIP FUNCTIONS
-- These functions aggregate child records for many-side relationships
-- ============================================================================

-- ============================================================================
-- INVERSE RELATIONSHIP FUNCTIONS
-- These functions perform reverse FK lookups for inverse-side relationships
-- ============================================================================



-- === 6. Custom functions (ERBCustomizations) ===
-- (no ERBCustomizations row for this section)

-- === 7. Recreate vw_* views ===============================================
-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Views: 13
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Drop pass: every rulebook-owned view, reverse iteration order, CASCADE.
-- The rulebook is HEAD — the surviving view set must mirror it exactly.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_landing_page_item_facts CASCADE;
DROP VIEW IF EXISTS vw_landing_page_items CASCADE;
DROP VIEW IF EXISTS vw_landing_page_sections CASCADE;
DROP VIEW IF EXISTS vw_landing_pages CASCADE;
DROP VIEW IF EXISTS vw_education_entries CASCADE;
DROP VIEW IF EXISTS vw_resume_list_items CASCADE;
DROP VIEW IF EXISTS vw_resume_variants CASCADE;
DROP VIEW IF EXISTS vw_job_entries CASCADE;
DROP VIEW IF EXISTS vw_proof_points CASCADE;
DROP VIEW IF EXISTS vw_how_i_work_sections CASCADE;
DROP VIEW IF EXISTS vw_bio_variants CASCADE;
DROP VIEW IF EXISTS vw_currently_items CASCADE;
DROP VIEW IF EXISTS vw_site_settings CASCADE;

-- ----------------------------------------------------------------------------
-- vw_site_settings: Singleton table of site-wide facts: contact info, positioning statement, and the undated 'Currently' block. One row.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_site_settings CASCADE;
CREATE VIEW vw_site_settings WITH (security_invoker = ON) AS
SELECT
  t.site_setting_id,                                                            -- Stored identity of the singleton settings row.
  calc_site_settings_name(t.site_setting_id) AS name,                           -- Display alias.
  t.contact_email,                                                              -- Primary contact email, shown in the Contact section on Home and Work.
  t.contact_phone,                                                              -- Contact phone number, as it appears on the resume header.
  t.site_domain,                                                                -- Canonical site domain.
  t.portfolio_company_count,                                                    -- Standardized portfolio count string, per Content Strategy Section 6 ('100+' everywhere, never 107 or 111).
  t.self_description_line,                                                      -- The 'full stack product practitioner' anchor phrase. Per Section 2: say it once, never next to a list.
  t.positioning_statement,                                                      -- The core positioning paragraph everything else derives from (Content Strategy Section 2).
  t.hero_headline,                                                              -- The large opening line of the Home hero, first person. First sentence of PositioningStatement, curated separately so the hero can style it distinctly from HeroSubheadline.
  t.hero_subheadline,                                                           -- The medium-sized second line of the Home hero, directly under HeroHeadline. Second/third sentence of PositioningStatement.
  t.banyan_title                                                                -- Full Banyan title, used everywhere per Section 6: 'Technical Advisor, Product Strategy and UX'.
FROM site_settings t;

-- ----------------------------------------------------------------------------
-- vw_currently_items: Table: CurrentlyItems. The undated 'Currently' block on Home (Section 10): a short bulleted list of what David is working on now. Update items when something changes, not on a schedule.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_currently_items CASCADE;
CREATE VIEW vw_currently_items WITH (security_invoker = ON) AS
SELECT
  t.currently_item_id,                                                          -- Stored identity, slug form.
  calc_currently_items_name(t.currently_item_id) AS name,                       -- Display alias.
  t.title,                                                                      -- The bullet's title/name, e.g. 'Banyan Software' or 'Lookout Together'.
  t.body_text,                                                                  -- The bullet's description text, under the title.
  t.sort_order                                                                  -- Display order.
FROM currently_items t;

-- ----------------------------------------------------------------------------
-- vw_bio_variants: Table: BioVariants. Five lengths plus one alternate, one spine, per David_Shadle_Bio_Set_v1.md. Voice standard applied: no em dashes, short sentences, active voice, no filler.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_bio_variants CASCADE;
CREATE VIEW vw_bio_variants WITH (security_invoker = ON) AS
SELECT
  t.bio_variant_id,                                                             -- Stored identity, slug form.
  calc_bio_variants_name(t.bio_variant_id) AS name,                             -- Display alias.
  t.label,                                                                      -- Human label for this bio length/context, e.g. 'Fifty words'.
  t.usage_context,                                                              -- Where this variant gets used, e.g. 'Directory listings, conference programs, deck footers, introductions.'
  t.body_text,                                                                  -- The bio copy itself. Paragraph breaks encoded as \n\n.
  t.sort_order                                                                  -- Display order, shortest to longest.
FROM bio_variants t;

-- ----------------------------------------------------------------------------
-- vw_how_i_work_sections: Table: HowIWorkSections. The method statement for the How I Work page, per David_Shadle_How_I_Work_v1.md. Written to be true indefinitely.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_how_i_work_sections CASCADE;
CREATE VIEW vw_how_i_work_sections WITH (security_invoker = ON) AS
SELECT
  t.how_i_work_section_id,                                                      -- Stored identity, slug form.
  calc_how_i_work_sections_name(t.how_i_work_section_id) AS name,               -- Display alias.
  t.heading,                                                                    -- Section heading as it appears on the page.
  t.body_text,                                                                  -- Full-page body copy for this section. Paragraph breaks encoded as \n\n.
  t.short_body_text,                                                            -- Condensed ~1-paragraph version, used if How I Work becomes a Home section instead of its own page. Null where the short version drops the section entirely.
  t.sort_order                                                                  -- Display order on the page.
FROM how_i_work_sections t;

-- ----------------------------------------------------------------------------
-- vw_proof_points: Table: ProofPoints. The proof inventory from Content Strategy Section 4. Raw material for the Work page and the resume's Selected Work block. Nothing goes into a bio, resume, or Work page entry that is not traceable to a row here.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_proof_points CASCADE;
CREATE VIEW vw_proof_points WITH (security_invoker = ON) AS
SELECT
  t.proof_point_id,                                                             -- Stored identity, slug form, matches Content Strategy subsection (e.g. 'pm-portal' for 4.2).
  calc_proof_points_name(t.proof_point_id) AS name,                             -- Display alias.
  t.title,                                                                      -- Short title for this proof point.
  t.problem_text,                                                               -- The problem, as stated in the proof inventory.
  t.action_text,                                                                -- The action taken.
  t.outcome_text,                                                               -- The outcome.
  t.attribution_note,                                                           -- Precise attribution language required when describing this work (e.g. 'advised on and implemented,' not 'owned'). See Content Strategy Section 6.
  t.register_note,                                                              -- Internal guidance on tone/register for this proof point. Not published copy - for whoever writes site/resume text from this row.
  t.client_or_category,                                                         -- Client name where nameable, otherwise a category label (e.g. 'Medical technology'). Shown as the first half of the Projects page meta row.
  t.status_label,                                                               -- Short status/type word for the Projects page meta row (e.g. 'Live in production', 'Problem brief').
  t.featured_on_work_page,                                                      -- Whether this proof point is one of the 2-3 engagements shown on the Work page (Section 10). First-pass selection - confirm with David before Phase 2.
  t.featured_in_resume_selected_work,                                           -- Whether this proof point appears in the resume's 'Selected work, 2024 to 2026' block (Variant A).
  t.image_url,                                                                  -- Public URL of this project's single representative image (hosted in Cloudflare R2). Optional — shown on the Work page when set.
  t.sort_order                                                                  -- Order matching Content Strategy Section 4 numbering.
FROM proof_points t;

-- ----------------------------------------------------------------------------
-- vw_job_entries: Table: JobEntries. Career history, shared by both resume variants via inclusion flags rather than duplicated per variant. Rows are grouped by DisplayGroupKey where a variant collapses multiple rows into one displayed entry (e.g. Variant A merges the two Power Automate roles).
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_job_entries CASCADE;
CREATE VIEW vw_job_entries WITH (security_invoker = ON) AS
SELECT
  t.job_entry_id,                                                               -- Stored identity, slug form.
  calc_job_entries_name(t.job_entry_id) AS name,                                -- Display alias.
  t.company,                                                                    -- Employer or entity name.
  t.job_title,                                                                  -- Title held. Null on the single synthetic 'earlier roles' compressed row.
  t.start_date,                                                                 -- Start, YYYY-MM.
  t.end_date,                                                                   -- End, YYYY-MM. Null if current.
  t.is_current,                                                                 -- True if this role is ongoing.
  t.display_group_key,                                                          -- Rows sharing this key render as one entry in Variant A (which uses the coarser grouping). Null where no grouping applies.
  t.summary_text_variant_a,                                                     -- Prose summary as it appears in Resume Variant A. On a grouped pair, only the earliest row in the group carries the merged text; the later row is null and the app renders the group using the earliest row's text with the group's full date range.
  t.summary_text_variant_b,                                                     -- Bullet-point summary as it appears in Resume Variant B, bullets joined with \n.
  t.compressed_line,                                                            -- One-line compressed text, used only on the synthetic 'earlier roles' row for Variant A's single-line pre-2019 summary.
  t.include_in_variant_a,                                                       -- Whether this row is shown (individually or as part of a group) on Resume Variant A.
  t.include_in_variant_b,                                                       -- Whether this row is shown on Resume Variant B.
  t.is_pre2019,                                                                 -- True for roles before 2019, compressed in Variant A per Content Strategy Section 7.
  t.sort_order                                                                  -- Reverse chronological display order.
FROM job_entries t;

-- ----------------------------------------------------------------------------
-- vw_resume_variants: Table: ResumeVariants. Two variants, one spine, per David_Shadle_Resume_Variants_v1.md. Variant A is public/served from the site; Variant B is sent directly and never published.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_resume_variants CASCADE;
CREATE VIEW vw_resume_variants WITH (security_invoker = ON) AS
SELECT
  t.resume_variant_id,                                                          -- Stored identity, slug form.
  calc_resume_variants_name(t.resume_variant_id) AS name,                       -- Display alias.
  t.label,                                                                      -- Variant label.
  t.audience_description,                                                       -- Who this variant targets and how it is distributed.
  t.summary_text,                                                               -- The opening capability statement ('What I do' / 'Summary'). Paragraph breaks encoded as \n\n.
  t.published_on_site                                                           -- Whether this variant is served from the public site (Section 10: only Variant A).
FROM resume_variants t;

-- ----------------------------------------------------------------------------
-- vw_resume_list_items: Table: ResumeListItems. The Methods and Technical blocks, shared identically by both resume variants, replacing the old comma-separated skills paragraph.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_resume_list_items CASCADE;
CREATE VIEW vw_resume_list_items WITH (security_invoker = ON) AS
SELECT
  t.resume_list_item_id,                                                        -- Stored identity, slug form.
  calc_resume_list_items_name(t.resume_list_item_id) AS name,                   -- Display alias.
  t.category,                                                                   -- 'Methods' or 'Technical'.
  t.label,                                                                      -- The item text as it appears on the resume.
  t.sort_order                                                                  -- Display order within its category.
FROM resume_list_items t;

-- ----------------------------------------------------------------------------
-- vw_education_entries: Table: EducationEntries.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_education_entries CASCADE;
CREATE VIEW vw_education_entries WITH (security_invoker = ON) AS
SELECT
  t.education_entry_id,                                                         -- Stored identity, slug form.
  calc_education_entries_name(t.education_entry_id) AS name,                    -- Display alias.
  t.institution,                                                                -- School name.
  t.degree,                                                                     -- Degree earned.
  t.field_of_study,                                                             -- Major/field.
  t.grad_year                                                                   -- Graduation year.
FROM education_entries t;

-- ----------------------------------------------------------------------------
-- vw_landing_pages: Table: LandingPages. One promotional landing page per row, reachable only by its direct URL. LandingPageId is the URL slug.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_landing_pages CASCADE;
CREATE VIEW vw_landing_pages WITH (security_invoker = ON) AS
SELECT
  t.landing_page_id,                                                            -- Stored identity. The URL slug, for example idea-to-evidence.
  calc_landing_pages_name(t.landing_page_id) AS name,                           -- Display alias.
  t.meta_title,                                                                 -- Browser title and Open Graph title.
  t.meta_description,                                                           -- Meta description and Open Graph description.
  t.eyebrow,                                                                    -- Small label above the headline in the hero.
  t.headline,                                                                   -- The page h1.
  t.lede,                                                                       -- Opening paragraph under the headline.
  t.video_url,                                                                  -- Optional YouTube link. When present, the video is shown in the hero between the eyebrow and the headline.
  t.primary_cta_label,                                                          -- Label of the primary call-to-action button.
  t.primary_cta_href,                                                           -- Target of the primary call-to-action button (mailto: or path).
  t.secondary_cta_label,                                                        -- Label of the optional secondary button.
  t.secondary_cta_href,                                                         -- Target of the optional secondary button.
  t.is_published                                                                -- Whether the page is served. Unpublished pages return 404.
FROM landing_pages t;

-- ----------------------------------------------------------------------------
-- vw_landing_page_sections: Table: LandingPageSections. The ordered sections of a landing page. Kind selects the renderer.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_landing_page_sections CASCADE;
CREATE VIEW vw_landing_page_sections WITH (security_invoker = ON) AS
SELECT
  t.landing_page_section_id,                                                    -- Stored identity, slug form.
  calc_landing_page_sections_name(t.landing_page_section_id) AS name,           -- Display alias.
  t.landing_page,                                                               -- The landing page this section belongs to.
  t.sort_order,                                                                 -- Display order within the page.
  t.kind,                                                                       -- Renderer: prose, list, steps, cards or callout.
  t.anchor_id,                                                                  -- Optional HTML id for the section, for in-page links.
  t.eyebrow,                                                                    -- Small label above the section heading.
  t.heading,                                                                    -- Section heading.
  t.body_text                                                                   -- Section body copy. Paragraph breaks encoded as \n\n.
FROM landing_page_sections t;

-- ----------------------------------------------------------------------------
-- vw_landing_page_items: Table: LandingPageItems. The ordered items inside a landing page section (cards, steps, list entries).
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_landing_page_items CASCADE;
CREATE VIEW vw_landing_page_items WITH (security_invoker = ON) AS
SELECT
  t.landing_page_item_id,                                                       -- Stored identity, slug form.
  calc_landing_page_items_name(t.landing_page_item_id) AS name,                 -- Display alias.
  t.landing_page_section,                                                       -- The section this item belongs to.
  t.sort_order,                                                                 -- Display order within the section.
  t.label,                                                                      -- Optional short marker, for example a step number.
  t.heading,                                                                    -- Item heading.
  t.body_text                                                                   -- Item body copy.
FROM landing_page_items t;

-- ----------------------------------------------------------------------------
-- vw_landing_page_item_facts: Table: LandingPageItemFacts. Labeled lines shown under a landing page item.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_landing_page_item_facts CASCADE;
CREATE VIEW vw_landing_page_item_facts WITH (security_invoker = ON) AS
SELECT
  t.landing_page_item_fact_id,                                                  -- Stored identity, slug form.
  calc_landing_page_item_facts_name(t.landing_page_item_fact_id) AS name,       -- Display alias.
  t.landing_page_item,                                                          -- The item this fact belongs to.
  t.sort_order,                                                                 -- Display order within the item.
  t.label,                                                                      -- Fact label, for example What happens.
  t.body_text                                                                   -- Fact text. One fact per line when it is a list.
FROM landing_page_item_facts t;



-- === 8. Custom views (ERBCustomizations) ===
-- (no ERBCustomizations row for this section)

-- === 9. Custom RLS (ERBCustomizations) ===
-- (no ERBCustomizations row for this section)

-- NOTE: the RBAC policy layer is generated by
-- effortless-rbac-to-postgres-policies as
-- drop-update-effortless-postgres-policies.sql. It follows this same
-- drop-and-recreate model and must run AFTER this file, because policies
-- reference the columns and views rebuilt above.

-- === 10. Custom data (ERBCustomizations) ===
-- (no ERBCustomizations row for this section)

COMMIT;
